autodesk-forks/MaterialX

source/MaterialXTest/Main.cpp

Turn off setting which makes debug output only go to visual studio debugger.

Make test output on Windows route to cout again

---

.appveyor.yml
.travis.yml

- Add build rules for creating artifacts and depolying to github repo for both appveyor and travis.
- For now we are triggered based on a git tag being specified or updates to adsk_update_shadergen

Add rules for building Artifacts

---

.appveyor.yml

- only build zip after deploy
- make deploy be on adsk_update instead of adsk_update_shadergen to reduce deploy count.

Artifact rule update

---

source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslSyntax.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxSyntax.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxSyntax.h
source/MaterialXShaderGen/Syntax.cpp

Added syntax class for OgsFx to handle a difference between GLSL and OgsFx in how vector uniforms are initialized.

Shadergen syntax class for OgsFx

---

source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXTest/Document.cpp

As pointed out by Bernard, perhaps the function should be renamed from getElementByPath to something else. Bernard recommended getChildByPath or just extending getChild, my only concern with this is that the result could be a descendant that is more than one level deep, so technically not a child, but a descendant. Thoughts appreciated.

New Element::getElementByPath function.

---

source/MaterialXShaderGen/HwShaderGenerator.cpp
source/MaterialXShaderGen/HwShaderGenerator.h
source/MaterialXTest/ShaderGen.cpp

Now using NodeDef of the light shader instead of the SgImplementation which a user had to search for.

Simplified interface for HwShaderGenerator::bindLightShader(). 

---

documents/Examples/SubGraphs.mtlx
documents/Libraries/sx/impl/shadergen/glsl/impl.mtlx
documents/Libraries/sx/impl/shadergen/glsl/source/sx_layeredbsdf.glsl
documents/Libraries/sx/impl/shadergen/glsl/source/sx_mixbsdf.glsl
documents/Libraries/sx/impl/shadergen/glsl/source/sx_mixedf.glsl
documents/Libraries/sx/impl/shadergen/glsl/source/sx_uniformedf.glsl
documents/Libraries/sx/sx_defs.mtlx
source/MaterialXShaderGen/SgNode.cpp
source/MaterialXShaderGen/Shader.cpp
source/MaterialXShaderGen/ShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerator.h
source/MaterialXShaderGen/ShaderGenerators/Common/Compound.cpp
source/MaterialXShaderGen/ShaderGenerators/Common/Swizzle.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightCompoundGlsl.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightCompoundGlsl.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightGlsl.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightGlsl.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightShaderGlsl.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightShaderGlsl.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/SurfaceGlsl.cpp
source/MaterialXShaderGen/ShaderGenerators/Osl/OslShaderGenerator.cpp
source/MaterialXShaderGen/Syntax.cpp
source/MaterialXShaderGen/Syntax.h
source/MaterialXTest/ShaderGen.cpp

- Support for light shaders implemented by graphs (light compounds)
- Separate handling of light shaders implemented by source code and light shaders implemented by graphs
- Added light compound example to test suite
- Cleanup of deprecated nodes in ShaderX library

More improvements to light shaders:

---

.travis.yml

Only build debug/relwithdebug for tagged releases to speed up CI time.

Conditional tag builds for travis.

---

source/MaterialXFormat/XmlIo.cpp

Move XML write predicate check to happen before xinclude writes. To be able to control xincludes as well with the predicate.

Move XML write predicate check

---

source/MaterialXShaderGen/HwShader.cpp
source/MaterialXShaderGen/SgNode.cpp
source/MaterialXShaderGen/SgNode.h
source/MaterialXShaderGen/ShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerator.h
source/MaterialXShaderGen/ShaderGenerators/Common/Compound.cpp
source/MaterialXShaderGen/ShaderGenerators/Common/Swizzle.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslSyntax.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslSyntax.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerators/Osl/OslShaderGenerator.cpp
source/MaterialXShaderGen/Syntax.cpp
source/MaterialXShaderGen/Syntax.h

Unconnected filename inputs for texture nodes where previously published from within a graph through the graph interface. Now this is simplified by just creating sampler uniforms for the textures directly, without having to add new graph interface ports on possibly multiple levels.

Improved handling of file textures in GLSL. 

---

documents/Libraries/stdlib/sx-osl/mx_image_color2.osl
documents/Libraries/stdlib/sx-osl/mx_image_color3.osl
documents/Libraries/stdlib/sx-osl/mx_image_color4.osl
documents/Libraries/stdlib/sx-osl/mx_image_float.osl
documents/Libraries/stdlib/sx-osl/mx_image_vector2.osl
documents/Libraries/stdlib/sx-osl/mx_image_vector3.osl
documents/Libraries/stdlib/sx-osl/mx_image_vector4.osl
documents/Libraries/stdlib/sx-osl/mx_tangent_vector3.inline
documents/Libraries/sxpbrlib/sx-glsl/sx_coatingbsdf.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_diffusebsdf.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_metalbsdf.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_normalmap.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_refractionbsdf.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_translucentbsdf.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_transparentbsdf.glsl
documents/Libraries/sxpbrlib/sx-osl/lib/sx_fresnel.osl
documents/Libraries/sxpbrlib/sx-osl/sx_coatingbsdf.osl
documents/Libraries/sxpbrlib/sx-osl/sx_diffusebsdf.inline
documents/Libraries/sxpbrlib/sx-osl/sx_edgetint.osl
documents/Libraries/sxpbrlib/sx-osl/sx_metalbsdf.osl
documents/Libraries/sxpbrlib/sx-osl/sx_normalmap.osl
documents/Libraries/sxpbrlib/sx-osl/sx_refractionbsdf.osl
documents/Libraries/sxpbrlib/sx-osl/sx_translucentbsdf.inline
documents/Libraries/sxpbrlib/sx-osl/sx_transparentbsdf.inline
documents/Libraries/sxpbrlib/sxpbrlib_defs.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_ng.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_sx-glsl_impl.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_sx-osl_impl.mtlx
source/MaterialXShaderGen/ShaderGenerators/Osl/OslShaderGenerator.cpp
source/MaterialXTest/ShaderGen.cpp

Improvements to OSL surface shading:
- Improved implementation for coatingbsdf and metalbsdf
- Added anisotropy to refractionbsdf
- Added conductor and dielectric fresnel functions
- Added optimization for image nodes when no texture file is given
- Fixed tangent node implementation
BSDF improvements and bugfixes:
- Fixed bugs with fresnel weighting in coatingbsdf
- Added a weight parameter to each BSDF. Needed for coating to be able to get correct layering when coat is disabled. (Still indecisive if it's good design to have on all other BSDF nodes, but for now including on all for consistency).
- Made separate normal map implementation for OSL vs GLSL since OSL needed a different tangent basis

ShaderX: Improvements to OSL surface shading

---

source/MaterialXShaderGen/HwShader.cpp

Use explicit vs computated rotation matrix to avoid precision inaccuracies that when written out can produce numbers which are invalid for a hw shader compiler. TBD how to handle this in general. (setf(ios_base::fixed)?).

Use explicit rotation matrix to avoid scientific notation usage for hw shader output

---

documents/Libraries/stdlib/sx-glsl/mx_image_color2.glsl
documents/Libraries/stdlib/sx-glsl/mx_image_color3.glsl
documents/Libraries/stdlib/sx-glsl/mx_image_color4.glsl
documents/Libraries/sxpbrlib/sx-glsl/lib/sx_lighting.glsl

Was using a hard-coded 2.2 gamma lookup. Remove this for now as this adversely affects image display.
Add in proper CM lookup later.

Remove hard-coded gamma for IBL and image lookup.

---

source/MaterialXShaderGen/SgNode.cpp
source/MaterialXTest/ShaderGen.cpp

- Handle if there an <interfacename> on a node is specified without it being specified on the nodedef.  
- Add output of generated materials to mtlx file for ShaderGen test.

Add fallback if no input on nodedef for interfacename

---

documents/Libraries/sxpbrlib/sxpbrlib_defs.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_ng.mtlx

Make standard surface conform to naming standard by add __\<type\> to the node definition name.

Minor fix to standard surface nodedef naming.

---

documents/Libraries/stdlib/sx-osl/mx_image_color2.osl
documents/Libraries/stdlib/sx-osl/mx_image_color3.osl
documents/Libraries/stdlib/sx-osl/mx_image_color4.osl
documents/Libraries/sxpbrlib/sx-glsl/sx_srgb_linear_color2.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_srgb_linear_color3.glsl
documents/Libraries/sxpbrlib/sx-glsl/sx_srgb_linear_color4.glsl
documents/Libraries/sxpbrlib/sx-osl/sx_srgb_linear_color2.osl
documents/Libraries/sxpbrlib/sx-osl/sx_srgb_linear_color3.osl
documents/Libraries/sxpbrlib/sx-osl/sx_srgb_linear_color4.osl
documents/Libraries/sxpbrlib/sxpbrlib_defs.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_sx-glsl_impl.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_sx-osl_impl.mtlx
source/MaterialXShaderGen/SgNode.cpp
source/MaterialXShaderGen/SgNode.h
source/MaterialXTest/ShaderGen.cpp

- Removed hard coded gamma correction from OSL <image> implementations
- Added tracking of color space usage for file texture nodes during graph traversal
- Added support for insertion of color transform nodes in graph finalization
- Added a simple sRGB color transformation node (just gamma 2.2 for now)
- Added a new test case for color spaces

Improvements to color management

---

source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

- Rework validation code to have some re-usable utilities.
- Remap geometry, lighting tests and split into 2.

Generalize ShaderX validation tests

---

documents/Libraries/stdlib/stdlib_sx-glsl_impl.mtlx
documents/Libraries/stdlib/sx-glsl/mx_premult_color2.glsl
documents/Libraries/stdlib/sx-glsl/mx_premult_color3.glsl
documents/Libraries/stdlib/sx-glsl/mx_premult_color4.glsl
documents/Libraries/stdlib/sx-glsl/mx_unpremult_color2.glsl
documents/Libraries/stdlib/sx-glsl/mx_unpremult_color3.glsl
documents/Libraries/stdlib/sx-glsl/mx_unpremult_color4.glsl
source/MaterialXTest/ShaderGen.cpp

* Add premulti/unmult implementations for glsl
* Add some temporary filtering of node types to figure implementations out for.
** filter out lights on purpose for osl

MateriaX 1.36 implementation updates

---

documents/TestSuite/stdlib/texture/image.mtlx
documents/TestSuite/stdlib/texture/tiledimage.mtlx
documents/TestSuite/stdlib/texture/triplanarprojection.mtlx

- Add in tiled image support
- Add in triplanar support (to verify when testing node-graph nodes but appears only 1 of the 3 planes blends properly in hardware).

Tiled image and triplanar test suite data

---

source/MaterialXGenOsl/ArnoldShaderGenerator.cpp
source/MaterialXGenOsl/ArnoldShaderGenerator.h
source/MaterialXGenOsl/OslSyntax.cpp
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp
source/MaterialXView/ShaderValidators/Osl/OslValidator.cpp
source/MaterialXView/ShaderValidators/Osl/OslValidator.h

- Add in disallowed closure definions for OSL and Arnold
- Set ShaderGen to output results to "results" folder
- Add an output file name for oslc generation so that oso files are placed beside osl files. This is required for testshade testing for example.
- Add in proper ifdef protections which are set based on generator build options.

Update for using OSL 1.9.10 distro build

---

documents/Libraries/stdlib/stdlib_ng.mtlx

Fixes to ramp node graph implementation from ILM.
Note that the index exposure was already added locally so does not show up in this PR.

Fixes for ramp nodegraph implementation from ILM.

---

documents/TestSuite/sxpbrlib/bsdf/bsdf_graph.mtlx
documents/TestSuite/sxpbrlib/bsdf/transmission.mtlx
source/MaterialXGenGlsl/Nodes/HeightToNormalGlsl.cpp

As node values are published via interfacename we require the nodedef to have default values otherwise everything renders black (using 0 as default values).

Fix bsdf unit test

---

.appveyor.yml

- Remove x86 and relwithdebug builds for /dev branches.

Reduce build overhead for Windows CI for dev branches.

---

source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp

- Was outputting with a uniform qualifier vs a const qualifier for pixel stage constant block.

Fix constant block output for OGSFX

---

source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/Shader.cpp
source/MaterialXGenShader/Shader.h

Remove logic to check document for vdirection as it is fixed as being UP based on the current specification. Leave the variable there in case there are any figure changes.

Spec conformance update: Remove check for vdirection based on Document

---

documents/TestSuite/_options.mtlx
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

- Options are specified in a mtlx file (_options.mtlx). It can reside at the top level of TestSuite but
subfolders can also contain this file to replace the parent folder options.

Add in data-driven unit test validation options 

---

documents/Libraries/stdlib/stdlib_sx-glsl_impl.mtlx
documents/Libraries/stdlib/stdlib_sx-glsl_ogsfx_impl.mtlx
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_color2.glsl
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_color3.glsl
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_color4.glsl
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_float.glsl
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_vector2.glsl
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_vector3.glsl
documents/Libraries/stdlib/sx-glsl/ogsfx/mx_image_vector4.glsl
documents/Libraries/stdlib/sx-osl/mx_image_color2.osl
documents/Libraries/stdlib/sx-osl/mx_image_color3.osl
documents/Libraries/stdlib/sx-osl/mx_image_color4.osl
documents/Libraries/stdlib/sx-osl/mx_image_float.osl
documents/Libraries/stdlib/sx-osl/mx_image_vector2.osl
documents/Libraries/stdlib/sx-osl/mx_image_vector3.osl
documents/Libraries/stdlib/sx-osl/mx_image_vector4.osl
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenOgsFx/OgsFxShaderGenerator.h
source/MaterialXGenOsl/ArnoldShaderGenerator.cpp
source/MaterialXGenOsl/ArnoldShaderGenerator.h
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.h
source/MaterialXGenShader/Shader.h
source/MaterialXGenShader/ShaderGenerator.cpp
source/MaterialXGenShader/ShaderGenerator.h
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

The vdirection option has been removed from MaterialX spec. To simplify generated code this change list removes the vdirection option feature from ShaderX. Instead each target can have special implementations for the <image> node in case a flip in texcoords v-component is needed for a target, depending on the targets definition of origin (0, 0) in texture space.
This change list also removes the OSL compile errors that was triggered by the vdirection generated code, as well as fixes a couple of other bugs found.

Removed the feature to set vdirection per target shader generator.

---

source/MaterialXRender/Handlers/Mesh.h

Reviewed by jstone in MaterialXView PR.

Add in missing identifier accessor for mesh.

---

source/MaterialXCore/Look.cpp
source/MaterialXCore/Look.h
source/MaterialXTest/Look.cpp

Add equivalent utility methods to those on Look to allow for variant assignment setting on MaterialAssign
Elements.

Add VariantAssign methods to MaterialAssign Element

---

documents/TestSuite/_options.mtlx
documents/TestSuite/stdlib/application/viewdirection.mtlx
source/MaterialXGenShader/Util.cpp
source/MaterialXTest/ShaderValid.cpp

- Turn on OGSFX by default and force on if impl count checking is turned since there are OGSFX impl variants for GLSL
- Add in viewdirection test
- Add in code to address Codacy warning for ifstream::read().
"Check buffer boundaries if used in a loop including recursive loops (CWE-120, CWE-20)"

ShaderX test suite updates.

---

source/MaterialXRender/OpenGL/GLCocoaWrappers.m

in GLCocoaWrappers.m:182:39:
error: cannot initialize a parameter of type 'NSOpenGLContextParameter' with an lvalue of type 'int'
[context getValues:vals forParameter:param];

Fix build error reported in Xcode

---

documents/Libraries/pbrlib/genglsl/mx_sheenbrdf.glsl
documents/Libraries/pbrlib/genglsl/mx_subsurfacebrdf.glsl
documents/Libraries/pbrlib/genglsl/pbrlib_genglsl_impl.mtlx
documents/Libraries/pbrlib/genosl/mx_mixsurface.osl
documents/Libraries/pbrlib/genosl/mx_sheenbrdf.osl
documents/Libraries/stdlib/osl/stdlib_osl_impl.mtlx
documents/TestSuite/pbrlib/materials/shader_ops.mtlx
documents/TestSuite/pbrlib/materials/surface_ops.mtlx
documents/TestSuite/stdlib/math/transform.mtlx
source/MaterialXGenShader/Util.cpp
source/MaterialXTest/ShaderValid.cpp

- Add more whitelisting for nodes like "dot", and string/filename constants
- Fix up some PBR library implementations:
- Add in missing surface and surface_shader tests
- Remove obsolete conicaledf implementation reference.

ShaderX Unit Test Updates

---

source/MaterialXGenShader/GenOptions.h
source/MaterialXGenShader/ShaderGraph.cpp

Reverted the change to remove the targetColorSpaceOverride option, since it's used by the MaterialXView project.

Reverted the removal of option targetColorSpaceOverride

---

source/MaterialXGenOsl/OslSyntax.cpp
source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h

- Fix for matrix33 as matrix output for OSL. Was inserting a 0.0 in the incorrect place. Also fixed up precision for output.
- Add in option to consider graphs connected to shader refers as renderable as an option as it's good for debugging inputs.

Matrix33 OSL variable output fix

---

source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXTest/ShaderValid.cpp

- Make sure to use valid root shader name for OSL and generating corresponding consistent source files 
names to use for setting up scene files for testrender.
- Note that  GLSL generation always uses the name "main" as the root function so it's okay there.

Disallow generating / using shader names which are invalid for OSL.

---

documents/TestSuite/Utilities/closure_color_scene.xml
documents/TestSuite/Utilities/constant_color_scene.xml
source/MaterialXFormat/File.h
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/Nodes/CompoundNode.cpp
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/Syntax.cpp
source/MaterialXGenShader/Syntax.h
source/MaterialXRender/Handlers/ImageHandler.cpp
source/MaterialXRender/Handlers/ImageHandler.h
source/MaterialXRender/OpenGL/GLTextureHandler.cpp
source/MaterialXRender/OpenGL/GLTextureHandler.h
source/MaterialXRender/OpenGL/GlslProgram.cpp
source/MaterialXRender/OpenGL/GlslProgram.h
source/MaterialXRender/ShaderValidators/Osl/OslValidator.cpp
source/MaterialXRender/ShaderValidators/Osl/OslValidator.h
source/MaterialXTest/ShaderValid.cpp

- Allow for image handler to have search paths 
- Allow for XML scene template to accept parameter overrides 
- During shader validation 
-- When reading input document, also include search path for exec + current doc path.
-- The image handler for GLSL has search paths added. For now it's the exec path + the path of the materialx file. For app integration any paths can be added.
-- The Shader is parsed to find filepaths and if relative will be converted to absolute paths and added as parameter overrides during XML scene instantiation from template.

Add relative path support for include files, images handlers and testrender scenes

---

CHANGELOG.md
python/MaterialXTest/main.py
source/MaterialXFormat/File.cpp
source/MaterialXFormat/File.h
source/MaterialXFormat/XmlIo.cpp
source/MaterialXTest/File.cpp
source/MaterialXTest/Node.cpp
source/MaterialXTest/XmlIo.cpp
source/PyMaterialX/PyMaterialXCore/PyUtil.cpp
source/PyMaterialX/PyMaterialXFormat/PyFile.cpp

- Modifications to localize warning disable for Windows getenv to just File.cpp (was global)
- Move file attribs from PyUtil to PyFile as they are part of MaterialXFormat and not MaterialXCore.

Merge from upstream master

---

documents/Libraries/pbrlib/pbrlib_defs.mtlx
documents/Libraries/pbrlib/pbrlib_ng.mtlx

Move copyright noticed after <?xml> tag so that the doc is valid.

Fix pbrlib xml copyright notices.

---

source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp
source/MaterialXGenOgsFx/OgsFxSyntax.cpp
source/MaterialXGenShader/Util.cpp
source/MaterialXRender/Handlers/GeometryHandler.h
source/MaterialXRender/Handlers/ImageHandler.h
source/MaterialXRender/Handlers/SampleObjLoader.cpp
source/MaterialXRender/Handlers/SampleObjLoader.h
source/MaterialXRender/ShaderValidators/ExceptionShaderValidationError.h
source/MaterialXRender/ShaderValidators/ShaderValidator.h
source/MaterialXRenderGlsl/GlslProgram.cpp
source/MaterialXRenderGlsl/GlslProgram.h
source/MaterialXRenderGlsl/GlslValidator.cpp
source/MaterialXRenderOsl/OslValidator.cpp
source/MaterialXTest/File.cpp
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/Render.cpp

- Rename TestObjLoader to SampeObjLoader
- Cleanup to use built in StringVec, StringMap and StringSet.

Render module cleanup

---

source/MaterialXView/Material.cpp
source/MaterialXView/Material.h
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

This change list adds a way to load in source code that was previously saved to file. This gives a simple way for debugging or experimenting with shader source code directly in the viewer, by editing the source before loading it in again.
To use this load in a material from .mtlx file and save out the generated source by pressing S-key as usual. Then find the produced source code files and start editing them. Pressing L-key will load in these edited source code files. Now you can iterate on the source by editing the files and pressing L-key to view the result in the viewer.

Added loading of material from source code.

---

source/MaterialXRender/Handlers/ImageHandler.cpp
source/MaterialXRender/Handlers/ImageHandler.h
source/MaterialXRender/Handlers/OiioImageLoader.cpp
source/MaterialXRender/Handlers/StbImageLoader.cpp
source/MaterialXRenderGlsl/GLTextureHandler.cpp
source/MaterialXRenderGlsl/GLTextureHandler.h
source/MaterialXRenderGlsl/GlslValidator.cpp
source/MaterialXTest/Render.cpp
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXRender/PyImageHandler.cpp

- Add in ImageBufferDeallocator function storage on an ImageDesc to allow for custom memory deallocation
- Fix up ImageHandler, derived ImageLoader classes and procedural constant color image generation to use this appropriately.
- Update Render tests to ensure calls. Was leaking memory before since CPU buffer deletion was not being called.

Make image buffer deallocation explicitly controlled

---

source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h
source/MaterialXTest/RenderGLSL.cpp
source/MaterialXTest/RenderOSL.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/RenderUtil.h
source/PyMaterialX/PyMaterialXRender/PyOiioImageLoader.cpp

Scan for multiple roots for gen and render unit tests:
- By default the test suite directory + standard surface examples are scanned.
- Render tests validation API can take in test roots + options file now for more flexibility.
- Fix for ImageHandler path for OIIO Python wrapper.

Scan for multiple roots for gen and render unit tests

---

source/MaterialXView/Editor.cpp
source/MaterialXView/Editor.h

Add scrolling pane for property editor. Needed to stop using form helper since it does not allow for a scroll pane to be inserted between the top window and the child widgets. There is greater control now for widget display so adding in group header with larger font and in bold.

Make Property Editor be scrollable.

---

resources/Materials/TestSuite/stdlib/adjustment/adjustment.mtlx

- Make hsv -> rgb test usable by performing rgb->hsv->rgb to make sure we get back the original value.
- Fix the smoothstep tests since they had 0 range values which would give undefined behaviour.

Fix adjustment unit tests

---

resources/Materials/TestSuite/_options.mtlx
source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXTest/GenArnold.cpp
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/GenOsl.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h
source/MaterialXTest/RenderArnold.cpp
source/MaterialXTest/RenderGLSL.cpp
source/MaterialXTest/RenderOSL.cpp
source/MaterialXTest/RenderOgsFx.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/RenderUtil.h
source/MaterialXView/Viewer.cpp

Fixes #419.
- Moved impl count check to GenShader.
- Move options structure and _options.mtlx input code to GenShader. 
- Gen* tests can now use _options.mtlx file for 
- Where to find options files
- Check for language/target inclusion
- Check for override file list (will still disable impl check if any specified)
- Check on whether to perform implementation count check. Main impetus of migration as this was only being performed in Render* tests which were not part of CI. Will now catch adding in new impls which are *not* tested to ensure full coverage at all times.

Migrate suitable options from Render* to Gen* unit tests

---

source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/RenderUtil.cpp

XML load was throwing exceptions and not being caught, thus halting all tests when:
1. scanning docs for gen* tests
2. validating a doc for render* tests.
Will now put out errors to the log files per file.

Fix to catch exceptions thrown on xml read during tests.

---

python/MaterialXTest/tests_to_html.py
resources/Materials/Examples/StandardSurface/standard_surface_velvet.mtlx
source/MaterialXView/Material.cpp
source/MaterialXView/Viewer.cpp

Affects #406, #416, #394 
- Fix env placement for viewer
- Add fallback in case png load fails for OIIO. Use stb instead
- Fix possible crash when doc load fails. Can't put up a document w/o a parent widget will just crash reading through null memory in nano-gui.
- Add in missing velvet shader from ILM.
- Fix html script as both width + height need to be specified when reading in as word document otherwise height stays same as original Chrome handles this properly.

Misc rendering configuration fixes.

---

source/MaterialXFormat/XmlIo.cpp
source/MaterialXTest/XmlIo.cpp

Update #394
- Pre-pend parent path to include search path to allow for includes with relative pats relative to a to parent without explicitly knowing the parent path.
- Note that the parent could also be relative. In this manner a hierarchy of sub-folder includes is possible without any absolute paths being specified.
- This relies on source URIs being set at the proper time (parent must be set before parsing children). 
- *Additional note* : During the read of the parent, a different source can be set than that of the actual filename (which could be relative or absolute). Thus a relative parent path can be set even when an absolute parent file name is used for actual reading.

Prepend parent paths when searching for child include files for document read.

---

libraries/bxdf/standard_surface.mtlx
libraries/pbrlib/genglsl/mx_fresnel_ior.glsl
libraries/pbrlib/genglsl/pbrlib_genglsl_impl.mtlx
libraries/pbrlib/genosl/mx_fresnel_ior.osl
libraries/pbrlib/genosl/pbrlib_genosl_impl.mtlx
libraries/pbrlib/pbrlib_defs.mtlx
libraries/stdlib/stdlib_defs.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_emission.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_sheen.mtlx
resources/Materials/TestSuite/pbrlib/bsdf/fresnel.mtlx

- Added a fresnel node to pbrlib.
- Use it for better approximation of emission when under coat in standard_surface implementation.
- Updated some material examples.

 Added a fresnel node to pbrlib

---

resources/Materials/TestSuite/stdlib/channel/channels_attribute.mtlx
resources/Materials/TestSuite/stdlib/color_management/color_management.mtlx
resources/Materials/TestSuite/stdlib/geometric/geomattrvalue.mtlx
source/MaterialXRenderGlsl/GlslProgram.cpp
source/MaterialXRenderOsl/OslValidator.cpp

*OSL png "failures"*
- Filter out erroneous libpng warnings from OSL render validation which just checks for any return strings from testrender.
*geomattrvalue*
- OSL doesn't bind anything so make GLSL bind black. Fix for program binding value as well to handle vectors.
*channels attribute*
- Fix arar channel test to avoid alpha blend differences for channels attr test.
- Fix channel attribute test to avoid mapping from alpha on an image as they are read differently in GLSL and OSL loaders.
*color management*
- Change the input image for color management as alpha from images are not read into OSL so results differ. Use grid texture in tests which has no alpha.
- Add missing test for unconnected constant acescg.

RTS test / test setup fixes

---

libraries/stdlib/genosl/mx_image_color2.osl
libraries/stdlib/genosl/mx_image_color3.osl
libraries/stdlib/genosl/mx_image_color4.osl
libraries/stdlib/genosl/mx_image_float.osl
libraries/stdlib/genosl/mx_image_vector2.osl
libraries/stdlib/genosl/mx_image_vector3.osl
libraries/stdlib/genosl/mx_image_vector4.osl
resources/Materials/TestSuite/stdlib/texture/image_addressing.mtlx
source/MaterialXRenderGlsl/GlslProgram.cpp
source/MaterialXView/Material.cpp

Fixes #447
- Fix up parsing of image uniforms to strip away the contents after last "_" vs stripping away everything after the first occurence of "_".
- Also fix implementations for OSL which did not use v address mode (only u) in the texture lookups.
Note: "black" means black color for outside the range in OSL but means "default color" in GLSL. Looking into extending spec, but unsure if OSL can handle this as "default" means something else.
- See issue for test results.

Fix GLSL texture setup and OSL address implementation for image node

---

source/MaterialXView/Material.cpp

Tested using the TestSuite\stdlib\geometric\streams.mtlx. bitangent nodes are now rendered.

Bind bitangent buffer for Viewer

---

libraries/pbrlib/genosl/mx_sheen_brdf.osl

- Added early out to sheen_brdf if weight is zero
- Fixed issue with unnormalized view direction causing indexing into sheen albedo table to go out of bounds (this is a short term fix, we should fix OSL testrender to normalize correctly)

Fixed issue with unnormalized view direction in OSL sheen_brdf.

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.h
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp
source/MaterialXContrib/MaterialXNode/MaterialXTextureOverride.cpp
source/MaterialXContrib/MaterialXNode/MaterialXTextureOverride.h
source/MaterialXContrib/MaterialXNode/resources/SR_brass1.xml
source/MaterialXContrib/MaterialXNode/resources/standard_surface_default.xml
source/MaterialXContrib/MaterialXNode/resources/tiledImage.xml
source/MaterialXContrib/OGSXMLFragmentWrapper.cpp
source/MaterialXContrib/OGSXMLFragmentWrapper.h
source/MaterialXTest/GenShader.cpp

Core work:
- Add xml version for brasss shader for testing.
- Add in global list and ouptut map list. 
- Globals are used to bind environment maps. Need to make sure to re-bind mip level and 
env matrix as these *do not get auto-bound* for some reason when creating the effect from xml?
- Fix template files to have V-flip for image lookup. Change test to also cause V-flip when
generating shader for the wrapper.
- FIx up world space position, normals and tangents to route using magic names Pw, Nw and Tw. 
-- Note that Nw get's *removed* from the shader during effect building for some reason if using a surface shader.  Need to assign to lambert for now to get it to not fail due to lack of Nw. 
Plug-in changes:
- Fix path and include issues
- Fix output path name setting as was using the …

Merge changes to support standard surface shader

---

cmake/modules/FindMaterialX.cmake

Updates based on comments from ILM
1) This utility goes far enough beyond the boilerplate USD version that I would say we should omit the explicit link and Pixar copyright.  Our goal here should be to provide the canonical FindMaterialX utility for others (including future versions of USD) to follow.
2) Instead of MATERIALX_STDSURF_DIR I would recommend a more generic MATERIALX_BXDF_DIR, since this folder will contain additional surface shaders in the future.

Updates to copyright and rename MATERIALX_STDSURF_DIR to MATERIALX_BXDF_DIR

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.h
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp
source/MaterialXContrib/MaterialXNode/MaterialXSurfaceOverride.cpp
source/MaterialXContrib/MaterialXNode/MaterialXTextureOverride.cpp
source/MaterialXContrib/MaterialXNode/resources/tiledImage.xml
source/MaterialXContrib/OGSXMLFragmentWrapper.cpp
source/MaterialXContrib/OGSXMLFragmentWrapper.h
source/MaterialXTest/GenShader.cpp

Update #445.
Cleanup in prep for switching from prototype Wrapper to new XML generator.
- Hide previous direct access to wrapper class to go through the MaterlalXData class.
- Hide more MaterialX specifics within the MaterialXData class
-- Make context part of class. Does not need to be dynamic for any reason.
-  Context still references a generator. Note we only ever need one generator (fragment XML generator to come).
-- Allow ability to set a new document / element.
- Minor function renames.
Cleanup binding for IBL and textures to make them more generic.
Minor cleanup on wrapper class to pre to make it align with XML fragment generator.

Clean up MaterialXData interfaces.

---

.gitignore
source/MaterialXView/Viewer.cpp

- AO was being drawn before transparent objects which would overwrite it. Move AO to be after. Neither is really correct as it should be done as part of lighting but okay for now.
- Fix so that left/right arrow cycling will update the UI properly. Got broken in some recent cleanup from master.

Viewer fixes for AO+transparency and UI updates for R/L material cycling

---

libraries/pbrlib/genglsl/pbrlib_genglsl_impl.mtlx
libraries/pbrlib/genosl/pbrlib_genosl_impl.mtlx
libraries/pbrlib/pbrlib_defs.mtlx
libraries/stdlib/genglsl/mx_normal_map.glsl
libraries/stdlib/genglsl/stdlib_genglsl_impl.mtlx
libraries/stdlib/genosl/mx_normal_map.osl
libraries/stdlib/genosl/stdlib_genosl_impl.mtlx
libraries/stdlib/stdlib_defs.mtlx
resources/Materials/TestSuite/libraries/metal/brass_wire_mesh.mtlx
resources/Materials/TestSuite/pbrlib/surfaceshader/surfaceshader.mtlx

Updates: #484 
- Move <normalmap> nodedef from pbrlib to stdlib and renamed to <normal_map>
- Change "tangent_space" to "space" string enum with "tangent" being the default.
- Add in normal "scale" input. Default value 1.0.

Rename and move normal map definition to stdlib

---

source/MaterialXContrib/MaterialXNode/resources/SR_brass1.xml
source/MaterialXContrib/MaterialXNode/resources/standard_surface_brass_tiled.xml
source/MaterialXContrib/MaterialXNode/resources/standard_surface_default.xml

Two takeaways:
1. The semantics of Pw, Nw and Tw have to match the names.
1. Nw has to be a varyingInputParam instead of a global (isRequirementOnly). This is because the pixel shader main function generated by VP2 preprocesses Nw before passing it to the main function of the fragment graph, e.g.
```vec3 v_Nw4738 = Nw( PIX_IN.Nw ); 
float v_facingFactor4739 = FacingFactor( mix( -1.0f, 1.0f, gl_FrontFacing ) ); 
bool v_mayaIsBackFacing4733 = mayaIsBackFacing( v_facingFactor4739 ); 
vec3 v_mayaNormalFlip4734 = mayaNormalFlip( v_Nw4738, v_mayaIsBackFacing4733, mayaNormalMultiplier, isSingleSided ); 
vec3 v_mayafloat3PassThrough4732 = mayafloat3PassThrough( v_mayaNormalFlip4734 ); 
```

MATX-198 - Fixed the missing Nw in manually edited standard_surface* fragment graphs.

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.h
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp
source/MaterialXContrib/MaterialXNode/Plugin.cpp
source/MaterialXContrib/MaterialXNode/Plugin.h
source/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
source/MaterialXGenOgsXml/OgsXmlGenerator.cpp

Update #445, MATX-217
- Nw must be treated as a non-global to be passed through properly when Effect generation occurs as additional processing is required.
- Fix so the semantic names to match the names for streams.
- Make sure to add Nw to the argument list for main function as it is no longer global. It is a dummy argument for now.
- Minor cleanup to move fragment registration to the command level. Clean up some hard-coded values / paths as well.
Results:
Here we show two shader graphs assigned to two sphere. The left-most is a texture graph assigned as a shader. Note the shaders/textures created as textures still works but is not shown here.

Add in new logic for handling of Nw stream

---

source/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
source/MaterialXGenOgsXml/GlslFragmentGenerator.h
source/MaterialXGenOgsXml/OgsXmlGenerator.cpp
source/MaterialXTest/GenOgsXml.cpp

Hack to publish matrix33 as matrix44 for OGS as it does not support a  matrix33 type.
* The XML parameters and function args are matrix44 which requires additional code to be inserted to convert them back to matrix33. 
* The paramater and args are use "dummy" generated names with an additional post-fix string appended.
* The destination of the conversion back to matrix33 use the original shader names.

Workaround fact that OGS does not have a matrix33 interface type.

---

source/MaterialXRender/ImageHandler.cpp
source/MaterialXRender/ImageHandler.h
source/MaterialXRenderGlsl/GLTextureHandler.cpp
source/MaterialXRenderGlsl/GLTextureHandler.h
source/MaterialXRenderGlsl/GlslProgram.cpp
source/MaterialXView/Material.cpp
source/MaterialXView/Material.h
source/MaterialXView/Viewer.cpp

Update #502 
Fix logic of managing used texture units. 
* Was just constantly using slots until full and then would stop allowing images to even load.
* Rework texture unit location handler to update on bind and newly added unbind. 
* Remove all updates from acquire as acquiring has nothing to do with binding. 
* Update viewer to use new logic by caching bound image names when drawing and then clearing the cache.

Fix logic of managing used texture units for ImageHandler 

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.h
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp
source/MaterialXContrib/MaterialXNode/MaterialXNode.h
source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.cpp
source/MaterialXContrib/MaterialXNode/MaterialXUtil.cpp
source/MaterialXContrib/MaterialXNode/MaterialXUtil.h

- The document attribute now holds a file path
- The document and element attributes are shown and are editable in the Attribute Editor
- MaterialXData updates on attribute changes.
There's definitely a lot of work to debug all the possible updates and loading and saving but at least it's not possible to create a MaterialX node via Hypershade, browse to a valid document from the document file path attribute in the Attribute Editor and get a working shader in the viewport.
I think it's time to decide on the final names of the document and element attributes and publish the spec.

MATX-194 - Document and element attributes are editable

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp

Just wanted to clean up the node and attribute names before making the interface final and exposing it to MtoA.

Renamed Maya node types and document and element attributes.

---

python/MaterialXTest/tests_to_html.py
resources/Materials/TestSuite/libraries/sd/floor.mtlx
source/MaterialXContrib/MaterialXNode/MaterialXUtil.cpp
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXGenShader/Util.cpp
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/XmlIo.cpp
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXCore/PyDocument.cpp
source/PyMaterialX/PyMaterialXCore/PyElement.cpp

Update #460 
- Merge from /dev to /materialx_node
- Need to keep CopyOptions for now as code will load libraries first and then import. There
does not appear to be a way to have the source URI comparison skip existing nodes as the imported document has no source URI.
- Also need to temporarily remove any references to xinclude files that occur more than once from different parents as well as includes which include some elements already in the document but have a different source URI.

Dev to MaterialXNode Merge 

---

source/MaterialXContrib/MaterialXNode/MaterialXData.cpp

Just a quick fix to the crash you mentioned @feldstj

Checking if the element is found in the document to prevent NULL dereferencing.

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp
source/MaterialXContrib/MaterialXNode/MaterialXNode.h
source/MaterialXGenOgsXml/OgsXmlGenerator.cpp

Maya expects surface nodes to have an outColor output attribute and complains if it's missing when creating our nodes in Hypershade.
It's also created statically now and no matter how the node is created (previously dynamically and from the command).
Also some cleanup.

Fixed the outColor attribute

---

source/MaterialXContrib/MaterialXNode/MaterialXNode.h
source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.cpp
source/MaterialXFormat/XmlIo.cpp

Update #460.
Add in texture root path which is the current documents path to find textures relative to document.

Find textures relative to document root path

---

source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/RenderUtil.cpp

Update #460 
- Add a search path for read so that includes can be searched for via… set of use paths + the current document path (previous)
- Filter out trying to render nodegraphs which are nodedefs.

Improve search path for document load + filter to not try and render nodedefs

---

source/MaterialXContrib/MaterialXNode/MaterialXData.cpp

Update MATX-206
Use default CM system for MaterialX Node generator. If one specified on the document use it. Otherwise use default linear (which is all that is currently supported).

MATX-206 : Use default CM system for MaterialX Node generator

---

resources/Materials/TestSuite/_options.mtlx
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h
source/MaterialXTest/RenderUtil.cpp

Add unit test options for external library paths and test roots in _options.mtlx.

Allow external tests with dependent external libraries for test suite.

---

source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.cpp
source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.h

With this change, the node updates correctly when the document or the element attribute values change. We should be able to make this work for the reload button as well - I'll investigate tomorrow.

MATX-195 - Fixed refreshing VP2 on document and element attribute changes.

---

source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/CreateMaterialXNodeCmd.h
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.h
source/MaterialXContrib/MaterialXNode/MaterialXNode.cpp
source/MaterialXContrib/MaterialXNode/MaterialXUtil.cpp
source/MaterialXContrib/MaterialXNode/MaterialXUtil.h

Migrate selection of renderable logic outside of constructor for MaterialXData.
Allow to iterate over all renderables if no explicit element name set.

Update logic for finding renderable elements if none is explicitly defined.

---

source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/GenContext.cpp

Fix #557.
Sanitize shader name for OSL (and in general any identifier). but have the identifier creator always perform name sanitizing. In case an attempt is made to create invalid identifiers elsewhere in the code.

Sanitize OSL shader names in code generation

---

source/MaterialXContrib/MaterialXNode/MaterialXUtil.cpp
source/MaterialXView/Viewer.cpp

Restore element conflict code lost in merge accidentally.
Required when include std libraries more than once.

Restore skip element checks

---

source/MaterialXView/Material.h
source/MaterialXView/Viewer.cpp

- Clear node definitions before calling generate for each material. Fix…es the case of UDIM load getting confused by reusing previous definitions. 
- Also fix so that if a material has a udim and it's using the same
materialX material element then only generate once and copy over the shaders references. Thus when editing in the property editor editing one edits all udim regions

UDIM fixes for Viewer

---

source/MaterialXView/Main.cpp

Minor change to allow specifying additional search paths. I'm using this for texture lookup at the moment. We need to do something similar for test config.
e.g.
--library adsklib --library adsklib/genglsl --path _path_to_library_ --path _path to textures_
The current implementation will overwrite the previous `-path` specified.

Append to search paths instead of replacing

---

source/MaterialXContrib/MaterialXMaya/README.md
source/MaterialXContrib/MaterialXMaya/scripts/MaterialXNodeUtil.py

While editing the readme I noticed that optionVar naming was inconsistent (cf. `materialXLibrarySearchPaths`). Searching in the Maya codebase shows that camelCase is standard for optionVars.

Renamed optionVar  MAYA_MATERIALX_EDITOR to materialXEditorPath.

---

CHANGELOG.md
libraries/pbrlib/genglsl/mx_roughness_dual.glsl
libraries/pbrlib/genosl/mx_roughness_dual.osl

Update #460 
- Restore isotropic fallback for roughness_dual
- Fix OSL implementation to avoid possible selt-modification of non-modifiable parameter. Test affected: shader_ops.mtlx
- Finalize changelog for v1.36.3

ILM Merge for 1.36.3 official release

---

source/MaterialXFormat/XmlIo.cpp
source/MaterialXFormat/XmlIo.h
source/MaterialXTest/XmlIo.cpp
source/MaterialXView/Viewer.cpp

Fixes: #556 
Remove development API which is a list of extra include files to check as part of write options.
- Instead have the application create it's own predicate which will filter out xincludes as it desires which is more flexible and basically performs the same action.
- Modify viewer to use this new logic and add in a unit test.

Use xinclude predicate versus xinclude list for write filtering

---

source/MaterialXRenderGlsl/GLCocoaWrappers.h
source/MaterialXRenderGlsl/GLCocoaWrappers.m

for NSOpenGLContextAuxiliary in NSOpenGLContextObj

Fix macOS deprecation error 

---

source/MaterialXContrib/MaterialXMaya/ShadingNodeOverrides.cpp

Looks like Clang is more picky than Microsoft compiler since building on Mac is returning following error: `error: declaration conflicts with target of using declaration already in scope`
Removing forward declaration of MPxShadingNodeOverride and MPxSurfaceShadingNodeOverride fix the problem.

OSX: Fix build error related to declaration already in scope

---

libraries/stdlib/stdlib_defs.mtlx
source/MaterialXCore/Definition.cpp
source/MaterialXCore/Definition.h
source/MaterialXCore/Document.cpp
source/MaterialXCore/Interface.cpp
source/MaterialXCore/Interface.h
source/MaterialXCore/Node.cpp
source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXTest/GenReference.cpp
source/MaterialXTest/Node.cpp
source/PyMaterialX/PyMaterialXCore/PyDefinition.cpp
source/PyMaterialX/PyMaterialXCore/PyInterface.cpp

Update #639, #385
Part I updates: Preliminary fixes for explicit outputs.
- Update of stddef for explicit outputs.
- Add in handing for non-typed nodedefs (e.g. "backdrop")
- Add in logic for handling "defaultinput" properly.
Part II prep: Nodedef remapping.
- Add in implementation generation test, which sanity check against updates in Part I.

1.37 signature changes : Part I.

---

source/MaterialXRuntime/Private/PrvStage.cpp
source/MaterialXRuntime/Private/PrvStage.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXRuntime/RtToken.h
source/MaterialXTest/Runtime.cpp

Update #638 
- Add input and output stream interfaces
- Add source URI storage for stages (is not part of attributes so could not be loaded or saved).
- Add source URI generation by scanning depending stages on write.
- Fix an issue with nodegraph read.
Not in this PR: stage child creation automatically being created for includes, other non-attribute Document level data.

RuntTime: Stream I/O and write source URI support

---

libraries/stdlib/stdlib_defs.mtlx
python/MaterialXTest/tests_to_html.py
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/Element.cpp
source/MaterialXCore/Node.cpp
source/MaterialXCore/Node.h
source/MaterialXTest/Node.cpp
source/PyMaterialX/PyMaterialXCore/PyNode.cpp

Update #682 
- `Backdrop` is now an explicit element. We derive from InterfaceElement to be able to use existing class support such as input/parameters. Which also is used for file I/O.
- Add in upgrade path + unit test.

1.37 Update : Migrate backdrop to no longer be a node.

---

source/MaterialXGenShader/GenContext.cpp
source/MaterialXGenShader/GenContext.h
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/GenOsl.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h

While running the "GenShader: OSL Shader Generation", "[genosl]" test, it is failing.
See issue #705 for more info.
This fix is adding a new method to be able to exclude specific files located in the libraries paths.

Fix vanilla osl test #705

---

source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXRuntime/RtPortDef.h
source/MaterialXTest/Runtime.cpp

Update #638 
Add addPort() interfaces to RtNodeGraph and RtNodeDef to simplify addition and have an interaces cooresponding to the removePort() method on each class.

Add addPort() interfaces for RtNodeGraph and RtNodeDef

---

source/MaterialXTest/CMakeLists.txt
source/MaterialXTest/GenReference.cpp

Fix #713.
Install osl include files into local reference directory so that generated files can use local include
references.

Fix up to add dependent includes to reference osl area

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h

This code creates a material element per surfaceshader node that is equivalent when saving a stage.

Adsk contrib/surface shader to material in runtime

---

python/Scripts/genmdl.py

Helper script:  
genmdl.py: Generate implementation directory for mdl based on existing MaterialX nodedefs in stdlib
Usage:  
genmdl.py \<library search path\> [\<module name\> \<version\>]
- A new directory called "library/stdlib/genmdl" will be created with two files added:'
- \<module_name\>.mdl: Module with signature stubs for each MaterialX nodedef
- "stdlib_genmdl_impl.mtlx": MaterialX nodedef implementation mapping file
- By default <module_name>="mymodule" and <version>="1.6"
e.g. output signature
_export color mx_splittb_color3
uniform color valuet = color(0.0, 0.0, 0.0)  
[[
anno::display_name(Top")
]],
uniform color valueb = color(0.0, 0.0, 0.0)  
[[
anno::display_name(Bottom")
]],
uniform float center = float(0.5)  
[[
anno::display_name(Center")
]],
varying float2 texcoord
) …

MDL impl directory generation script.

---

libraries/stdlib/stdlib_defs.mtlx
python/Scripts/genmdl.py

- Add in enumeration mapping
- Use swizzle for 2d texcoord lookup
- Add in texture resource usage vs string, but skip for actual filename constant nodedef (stays a string)
- use 'mxp_' prefix for parameters names to avoid keyword name clashes
- fix up defaultinput, defaultvalue support
- fix up when return type is 'material' type or 'multioutput' type 
Fix to stdlib.mtlx as 'normalmap' 'defaultinput' should be a 'default' attribute (since it's value, not routing an input)
Output validated using 'mdlc' with '-W "183=off"' to turn off unused parameter as warning.

Enumeration, texture resource usage for MDL script

---

.gitignore
python/MaterialXTest/main.py
resources/Materials/TestSuite/_options.mtlx
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/Interface.cpp
source/MaterialXCore/Interface.h
source/MaterialXCore/Node.cpp
source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/MaterialXFormat/XmlIo.cpp
source/MaterialXFormat/XmlIo.h
source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h
source/MaterialXTest/Observer.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/XmlIo.cpp
source/MaterialXView/Material.cpp
source/MaterialXView/Viewer.cpp

Update #616 
- Add in upgrade code from material element to material node.
- Update traversal logic to handle equivalent traversal on inputs as for bindinputs.
- Allow version to be chosen for file read to allow for 1.38 (materialnode) to be converted as desired.
- Options file can be set to 1.38 for shadergen but backend recognition logic to come.
Note that xmllio test runs against both 1.37.2 and 1.38 (w/o and w/ a materialnode)

Add in version option, materialnode upgrade + associated traversal logic.

---

resources/Materials/TestSuite/_options.mtlx
source/MaterialXCore/Look.cpp
source/MaterialXCore/Look.h
source/MaterialXGenOgsXml/OgsFragment.cpp
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/ShaderGraph.h
source/MaterialXGenShader/ShaderNode.h
source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXView/Material.h
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXCore/PyLook.cpp
source/PyMaterialX/PyMaterialXCore/PyUtil.cpp

Update #616 
- Add in new search logic to find renderable shader nodes and new transparency checker
- Modify shader generation to take in shader nodes as root node.
- Update render and generation tests to pass shader nodes to generators
- Update view to keep track of material nodes and shader nodes and use shader nodes to generate code. 
- Update texture baker to scan outputs on shader nodes for texture baking and to generate simplified document referencing the baked outputs.

Update to shading and rendering for material node support

---

source/MaterialXCore/Look.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXRuntime/RtLook.cpp
source/MaterialXRuntime/RtLook.h
source/MaterialXRuntime/RtRelationship.cpp
source/MaterialXRuntime/RtRelationship.h
source/MaterialXTest/Runtime.cpp

LOOKDEVX-4, LOOKDEVX-146: 
- Add ability to read/write collections, materialassigns, looks, and look groups
- Add in geom support for collections.
- Update unit tests.
- Add in version option on read to allow for material-node conversion (by default) on read.

LOOKDEVX-146 : Add in runtime file I/O for look information 

---

source/MaterialXRuntime/RtFileIo.cpp

Triggered by saving a scene with a LookdevX Graph.

Fixed a crash on NULL write options

---

CMakeLists.txt
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXTest/CMakeLists.txt
source/MaterialXTest/GenArnold.cpp
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenMdl.cpp
source/MaterialXTest/GenMdl.h
source/MaterialXTest/GenOgsXml.cpp
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/GenOsl.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h

- MATERIALX_BUILD_GEN_MDL : Option to build MDL or not
- MATERIALX_MDLC_EXECUTABLE : mdlc location
- MATERIALX_MDL_RENDER_EXECUTABLE : mdl renderer location
- MATERIALX_MDL_MODULE_PATHS : comma separated list of mdl module paths
Also fix osl generator as it was omiitting a "," in the main function signature so would not compile.

Add build options for MDL

---

libraries/bxdf/usd_preview_surface.mtlx
source/MaterialXTest/Runtime.cpp

Restore modifications made to usd material definition to make runtime load work.
Add in test to make sure this is always tested in the future.
A fix or validation check should be added to catch this in core/runtime later.

Fix USD definition load into runtime

---

source/MaterialXRuntime/RtLook.cpp
source/MaterialXTest/Runtime.cpp

Add in lookgroup->lookgroup child test + some additional type checking.
There are no changes required to the LookGroup definition but found that anything can be added as a lookgroup child. Add in type checking here + also for looks.

Lookgroup child testing

---

source/MaterialXFormat/File.h
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h
source/MaterialXTest/Runtime.cpp

- Add in separate texture and implementation search paths
- Add in a clear() as RtAPI is a singleton and never clears paths.

Add in additional runtime search paths

---

libraries/stdlib/genmdl/materialx/sampling.mdl
libraries/stdlib/genmdl/stdlib_genmdl_impl.mtlx
source/MaterialXGenMdl/MdlShaderGenerator.cpp
source/MaterialXGenMdl/Nodes/HeightToNormalNodeMdl.cpp
source/MaterialXGenMdl/Nodes/HeightToNormalNodeMdl.h
source/MaterialXGenShader/Nodes/ConvolutionNode.cpp
source/MaterialXTest/GenMdl.cpp

* Need to add in the custom node which will generate the MDL code required.
* Similar to the GLSL one with mostly the array syntax handling being different.
* Fix a small issue in code generation which would output a line with 2 semi-colons at the end of line ";;". This is consider to be invalid when checking with mdlc.

Add support for generating height-to-normalmap MDL code.

---

libraries/stdlib/stdlib_defs.mtlx
resources/Materials/TestSuite/stdlib/math/transform.mtlx
resources/Materials/TestSuite/stdlib/math/vector_math.mtlx
resources/Materials/TestSuite/stdlib/upgrade/1_36_to_1_37.mtlx
source/MaterialXTest/Units.cpp

Using https://physics.nist.gov/cuu/Units/units.html as a reference to use singular naming convention.
e.g. angle is 30 **degree** instead of **degrees**

Harmonization on singular unit names.

---

source/MaterialXGenShader/UnitConverter.cpp
source/MaterialXGenShader/UnitConverter.h
source/MaterialXRuntime/Private/PvtAttribute.cpp
source/MaterialXRuntime/Private/PvtAttribute.h
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h
source/MaterialXRuntime/RtAttribute.cpp
source/MaterialXRuntime/RtAttribute.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtStage.cpp
source/MaterialXRuntime/RtStage.h
source/MaterialXRuntime/RtTypeDef.h
source/MaterialXTest/Runtime.cpp

* Keep track of set of unit information at RtApi level. 
* Populate UnitConverterRegistry (which is Document independent) during library load. This is cumulative until a reset is performed.
* Add in "validation document" which has unit information added to it just for validation (not save)
based on the UnitConverterRegistry
* Add in unit tests.

LOOKDEVX-158 : Add support for units in Runtime

---

source/MaterialXRuntime/Private/PvtTypeDef.cpp
source/MaterialXTest/Runtime.cpp

Allow bool string to be "1" or "0" in addition to "true" or "false".
This will allow for any external system to set these values as it's not required that the string always be "true" / "false".

LOOKDEVX-163 : Handle "1" / "0" for boolean setting for Runtime Values

---

resources/Materials/TestSuite/_options.mtlx
source/MaterialXRender/ShaderRenderer.h
source/MaterialXRenderGlsl/GLFramebuffer.cpp
source/MaterialXRenderGlsl/GLFramebuffer.h
source/MaterialXRenderGlsl/GlslRenderer.cpp
source/MaterialXRenderGlsl/GlslRenderer.h
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h
source/MaterialXRenderOsl/OslRenderer.cpp
source/MaterialXRenderOsl/OslRenderer.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h
source/MaterialXTest/RenderGLSL.cpp
source/MaterialXTest/RenderOSL.cpp
source/PyMaterialX/PyMaterialXRender/PyShaderRenderer.cpp

Change:
* Add ability to set and reset rendered size (both width and height now vs just rendering square images)
* Accessible on GLFrameBuffer, and ShaderRenderer interfaces or directly in C++ / Python
* Expose in unit tests (via _options.mtlx) 
* GLSL and OSL render tests use new _options.mtlx option: `renderSize`. OSL just sends
arguments to external renderer.
* Rendering for material preview can use new option.
* Rendering for texture baking can use new option.
Example sizes:

Add size control to utility rendering

---

source/MaterialXTest/GenShaderUtil.cpp

Location of skipping nodedefs was not safe resulting in possible null ptr reads.

Fix crash due to bad merge.

---

libraries/adsk/adsklib/colorcorrect.mtlx
libraries/adsk/procedurals/colorcorrect.mtlx
libraries/adsk/shaders/wood/parquet_3/parquet_03.mtlx
source/MaterialXFormat/Util.cpp
source/MaterialXFormat/Util.h
source/MaterialXRuntime/Private/PvtApi.cpp
source/MaterialXRuntime/Private/PvtPrim.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXRuntime/RtPrim.h
source/MaterialXTest/MaterialXGenGlsl/GenGlsl.cpp
source/MaterialXTest/MaterialXGenOsl/GenOsl.cpp
source/MaterialXTest/MaterialXGenShader/GenShader.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.h
source/MaterialXTest/MaterialXRender/RenderUtil.cpp
source/MaterialXTest/MaterialXRender/RenderUtil.h
source/MaterialXTest/MaterialXRenderOsl/GenReference.cpp

- Add in initial definitions layout
- Add in sample colorcorrect and wood shader definitions
- Add support to allow interface of multiple roots being passed in to find child directories, and child directories. Cleanup to have 1 library load interface with all options.
- Fix to not require that the output be named "out". If a empty string is passed to getOutput() then the first output is returned.
Layout slightly expanded will look like this:
```
+---adsklib
|   |   adsklib_defs.mtlx
|   |   adsklib_ng.mtlx
|   |   colorcorrect.mtlx
|   |
|   +---genglsl
|   |       adsklib_genglsl_impl.mtlx
|   |       curvature.glsl
|   |
|   +---genmdl
|   |       adsklib_genmdl_impl.mtlx
|   |       curvature.mdl
|   |
|   \---genosl
|           adsklib_genosl_impl.mtlx
|           curvature.osl
| …
```

Library Definition Layout

---

source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenGlsl/Nodes/LightCompoundNodeGlsl.cpp
source/MaterialXGenGlsl/Nodes/LightNodeGlsl.cpp
source/MaterialXGenGlsl/Nodes/LightShaderNodeGlsl.cpp
source/MaterialXGenGlsl/Nodes/SurfaceNodeGlsl.cpp
source/MaterialXGenGlsl/Nodes/SurfaceShaderNodeGlsl.cpp
source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.h

Allow users to disable light loop and light structs for direct lights by setting `hwMaxActiveLightSources=0`

Use ShaderGen options to disable lights.

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

- Change to use metadata vs relationship for RtNodeDef / RtNodeGraph relathonship (which is not used anywhere)
- Add support create inputs on an RtNodeDef if there are inputs on a RtNodeGraph.
- Add support to write out an RtNodeDef + corresponding nodegraph (if exists).
- Add Runtime test to test save to MTLX.
- Note: there are issues in core with haveing a `version` attribute on a nodedef. Node::getNodeDef() does not seem to be able to find the corresponding nodegraph. See issue: #874.
The following is the result of the unit test which takes a RtNodeGraph and creates a RtNodeDef + modifies the RtNodeGraph. Test then saves and reloads to test validity.
```
<materialx version="1.37">
<nodedef name="ND_addgraph" node="addgraph" nodegroup="math" version="3.4">
<input …
```

Add support to write out RtNodeDefs to document

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtNode.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

- Fix so that version is set on RtNodes if the RtNodedef has a version. 
To verify the complete set which is required (e.g. `target` seems like it's required but to confirm)
- Make sure that target and version are settable on the RtNodedef and saved to MTLX.
- Fix to that empty metadata values are not saved.
Updated definition output looks like this:
```
<materialx version="1.38">
<nodedef name="ND_add_float" node="add">
<input name="in1" type="float" value="0" />
<input name="in2" type="float" value="0" />
<output name="out" type="float" value="0" />
</nodedef>
<nodegraph name="NG_addgraph" nodedef="ND_addgraph">
<input name="a" type="float" />
<input name="b" type="float" />
<add name="add1" type="float">
<input name="in1" type="float" interfacename="a" />
<input …
```

LOOKDEVX-235 : Fix up version handling in runtime

---

resources/Materials/TestSuite/pbrlib/surfaceshader/mapped_surfaceshader.mtlx
source/MaterialXCore/Interface.cpp
source/MaterialXGenShader/Util.h

Affects LOOKDEVX-182
Fix #883
Fix logic to find output from input so that it is optional. If not specified find the first 
output on any upstream node or nodegraph.
(Regression most like the result of some bad merges.)

Fix input traversal so "output" attribute is optional if nodename/nodegraph specified.

---

source/MaterialXGenShader/ShaderGraph.cpp

LOOKDEVX-257 : Allow "interfacenames" on inputs even if not a node definition.

---

source/MaterialXGenGlsl/GlslResourceBindingContext.cpp
source/MaterialXGenGlsl/GlslResourceBindingContext.h
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.h
source/MaterialXTest/MaterialXGenGlsl/GenGlsl.cpp
source/MaterialXTest/MaterialXGenGlsl/GenGlsl.h
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.h

This makes the MaterialX Codegen'ed GLSL shader more SPIR-V friendly and also Cross Compiler friendly. _However a side effect is that uniform initialization in the GLSL shader is not possible._
**Additional details:**
1. Separate and group uniforms:
The Hardware codegen will separate and group uniforms into three areas:
Private, Public and Sampler blocks
Public uniforms are inputs that should be published in a user interface for user interaction.
Private uniforms are internal variables needed by the system which should not be exposed in UI.
All texture based objects should be added to Sampler block
2. Emit uniform blocks with binding information
A new HwResourceBindingContext Interface and an implementation for `GlslResourceBindingContext 
`is added to allow GlslShaderGenerator to emit …

Enable GlslShaderGenerator to add `layout` in generated code.

---

libraries/bxdf/standard_surface.mtlx
libraries/pbrlib/genglsl/pbrlib_genglsl_impl.mtlx
libraries/pbrlib/genmdl/pbrlib_genmdl_impl.mtlx
libraries/pbrlib/genosl/pbrlib_genosl_impl.mtlx
libraries/pbrlib/pbrlib_defs.mtlx
resources/Materials/TestSuite/pbrlib/bsdf/layer_bsdf.mtlx
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenMdl/MdlShaderGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXGenShader/Nodes/LayerNode.cpp
source/MaterialXGenShader/Nodes/LayerNode.h
source/MaterialXGenShader/ShaderGenerator.cpp
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/ShaderNode.cpp
source/MaterialXGenShader/ShaderNode.h
source/MaterialXGenShader/ShaderNodeImpl.h

This change list adds a new `layer` node for doing vertical layering with an operator node.
Our existing BSDF nodes with layering support has not been changed. The new `layer` node is supported through codegen which generates the same layering code as with the existing BSDF nodes. In code it transforms the layering operator setup into a nested layering setup.
So now a user can choose to specify BSDF layering through either the same old nesting of BSDF's or through the new layer operator node. Mixing both methods in the same graph is not allowed, so you have to choose.
Examples comparing the syntaxes:
```
<nodegraph name="layer_bsdf_test1">
<diffuse_brdf name="diffuse_brdf_1" type="BSDF" />
<sheen_brdf name="sheen_brdf_1" type="BSDF">
<input name="base" type="BSDF" …
```

Support for vertical layering through a layer operator node.

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Put this up for discussion.
If loading in a library def file the current doc does not have existing definitions include geompropdef
so will fail validation.

LOOKDEVX-269: Add option for MTLX validation on Runtime read

---

source/MaterialXGenGlsl/GlslResourceBindingContext.cpp
source/MaterialXGenGlsl/GlslResourceBindingContext.h
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.h
source/MaterialXTest/MaterialXGenGlsl/GenGlsl.cpp
source/MaterialXTest/MaterialXGenGlsl/GenGlsl.h
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.h
source/PyMaterialX/PyMaterialXGenGlsl/PyGlslShaderGenerator.cpp
source/PyMaterialX/PyMaterialXGenShader/PyHwShaderGenerator.cpp

This change list fixes the regression with MaterialXView not binding any image textures. Change done is mainly to remove the explicit "sampler" variable block. Instead of keeping a separate block for sampler uniforms the split is handled when the uniforms are emitted.
Also addressed is an issue with generated uniform block names being the same in vertex vs pixel stages, causing compile errors. Fixed by appending the stage name to the uniform block name.
One remaining issue is how to handle binding layout for the LightData uniform block, this was not addressed in the previous PR (#896) and the LightData uniform struct is emitted without a layout directive. To be discussed further.
The following code is now emitted if a binding context is used:
```
#version 400
#extension …
```

Fix regressions with layout bindings.

---

resources/Materials/TestSuite/stdlib/convolution/heighttonormal_in_nodegraph.mtlx
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenGlsl/GlslSyntax.cpp
source/MaterialXGenGlsl/GlslSyntax.h
source/MaterialXGenGlsl/Nodes/HeightToNormalNodeGlsl.cpp
source/MaterialXGenGlsl/Nodes/HeightToNormalNodeGlsl.h
source/MaterialXGenMdl/MdlShaderGenerator.cpp
source/MaterialXGenMdl/MdlSyntax.cpp
source/MaterialXGenMdl/MdlSyntax.h
source/MaterialXGenMdl/Nodes/BlurNodeMdl.cpp
source/MaterialXGenMdl/Nodes/BlurNodeMdl.h
source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp
source/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenOsl/OslSyntax.cpp
source/MaterialXGenOsl/OslSyntax.h
source/MaterialXGenShader/Nodes/BlurNode.cpp
source/MaterialXGenShader/Nodes/BlurNode.h
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/ShaderNode.cpp
source/MaterialXGenShader/ShaderNode.h
source/MaterialXGenShader/Syntax.h
source/MaterialXTest/MaterialXRender/RenderUtil.cpp

Fix a bug triggered with using heighttonormal inside a nodegraph implementation (convolution classification was not tracked).
Instead of tracking the convolution classification, and emitting needed include files in the pixel stage, each convolution node is now responsible for emitting its own include files, if needed.

Fix handling of included functions for convolution nodes

---

source/MaterialXRuntime/Private/PvtPrim.cpp
source/MaterialXRuntime/Private/PvtPrim.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

This was a bigger change then I was hoping for, please take a look and let me know if you have any concerns. It seems to make things work on the LookdevX-side (separate review after this one assuming this is ok).

Correctly renames inputs, outputs, and nodes that have duplicate names.

---

source/MaterialXRenderGlsl/GlslProgram.cpp

Fix #914 
Fix binding issue if empty filename given to bind with. 
Remove skipping binding in that condition.

Fix GLSL texture binding when empty filename used.

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h

- Set writeNodeGraphInputs to false by default to not write out inputsockets. as nodegraph <inputs>
- Always write inputs on nodes even when connected to inputsockets.
- Update read to set inputsocket values based on the corresponding nodegraph node input value.

LOOKDEVX-290 : Change to not write inputsockets on file write.

---

libraries/pbrlib/genglsl/mx_sheen_brdf.glsl

Small fix to make the normal forward facing in sheen calculations. Sheen is particular sensitive to this and gives artifacts on backfacing surfaces without this fix.
We could introduce a more general handling of normal flipping later, to make it consistent for all our BSDF nodes.

Face forward fix to sheen brdf

---

libraries/bxdf/standard_surface.mtlx

Removed usage of swizzle-on-input from Standard Surface graph, since not all targets supports this. Replaced with an explicit swizzle node instead.

 Fix issue with standard surface opacity connection

---

libraries/adsk/adsklib/colorcorrect.mtlx
libraries/adsk/materials/wood/parquet_3/ND_parquet_03_material.mtlx
libraries/adsk/shaders/wood/parquet_3/ND_parquet_03_shader.mtlx
resources/Materials/TestSuite/adsklib/adsk_shaders.mtlx
resources/Materials/TestSuite/stdlib/version/my_add_versioned.mtlx
source/MaterialXCore/Definition.cpp
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXTest/MaterialXRender/RenderUtil.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Update #852 
- Add back in version check between nodedef and nodegraph implementation to allow for different implemenation versions per definition.
- Add in supporting code to ensure and check for compatible version support for RtNodeGraph/RtNodeDef.
- Add back in version setting for RtNodeGraph when publishing an RtNodeGraph.
- Add in version "compatibility" check when looking for an implementation (RtNodeGraph) for an RtNodeDef.
- Namespace and version parquet shader and material
- Add back in versioning for nodegraphs implementation on colorcorrect.
- Replace namespace characters for shadername used for render unit tests.
- Update unit tests.

LOOKDEVX-235 : Nodegraph version support (part 2).

---

resources/Materials/TestSuite/stdlib/definition/surfacematerial_definition.mtlx
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h

Fix save to MTLX so that a fullly namespaced node name is used when creating a new node in the Document.

Update RtRuntime MTLX node save to support namespacing support

---

libraries/adsk/materials/wood/parquet_3/ND_parquet_03_material.mtlx
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

1. Make the validation check in RtFileIO for nodedefs consider namespace (same as done for write).
2. Fix to remove hard-coded "out" check if output connections so graphs with different output names load properly.
3. Fix missing namespace in unit test file.
4. Add new Runtime test to read in unit test (3.) to test RtFile nodedef validation and connection fixes (1, 2).
5. Remove the older MTLX level validation as definition checking is sufficiently done at the Runtime level.
The definition errors without this would be:
```
- Could not read file: adsk_shaders.mtlx. 
Error: No matching nodedef was found for node 'colorcorrect'
```
when it should have looked for `adsk:colorcorrect` and
```
Error: "Node 'NG_parquet_03_shader` no output named 'out'  
```
which is an incorrect error as this …

LOOKDEVX-235 : Output port and Rt File I/O fixes for nodedef

---

libraries/pbrlib/genglsl/lib/mx_microfacet_specular.glsl

Update #584 
Initialize FresnelData to prevent errors during HLSL generation.
During GLSL --> HLSL conversion I was running to `error X4575: reading uninitialized value`
I added a simple constructor while keeping the current style to update members.

Initialize FresnelData

---

source/MaterialXGenGlsl/GlslResourceBindingContext.cpp
source/MaterialXGenGlsl/GlslResourceBindingContext.h
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenGlsl/Nodes/NumLightsNodeGlsl.cpp
source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXGenShader/HwShaderGenerator.h

Update #584
Glsl shaders with Structured uniforms e.g. lightdata cannot be Cross Compiled to other targets.
The main issue is that members of the structures need to be aligned.
This can cause SPIRV exceptions such as:
SPIRV-Cross threw an exception: cbuffer ID 4559 (name: LightData_pixel), member index 0 (name: u_lightData) cannot be expressed with either HLSL packing layout or packoffset
Added a new HwResourceBindingContext::emitStructuredResourceBindings that can be used to generate struct with binding information.
It also tries to arrange the members so that they are aligned by adding padding as needed.
e.g.
```
struct LightData
{
vec3 position;
vec3 color;
vec3 direction;
float outer_angle;
float inner_angle;
float decay_rate;
float intensity;
int type;
float pad0;
float pad1;
float …
```

Add resource binding for structured uniforms.

---

source/MaterialXGenGlsl/GlslResourceBindingContext.cpp
source/MaterialXGenGlsl/GlslResourceBindingContext.h
source/PyMaterialX/PyMaterialXGenGlsl/PyGlslShaderGenerator.cpp

All binding locations are contiguous at the moment. This separates them for Uniforms (b# registers) and Samplers (t# registers)
Also added ability to set initial value

Separate Binding Location for uniforms and samplers.

---

source/MaterialXCore/Library.h

With the latest VS2019 16.7 release, MaterialX fails to build (with e……rrors below).
Looks like this is caused by the internal changes from vs2019 16.6 to 16.7 release.
MaterialX\source\MaterialXCore\Element.cpp(753,32): error C2039: 'inserter': is not a member of 'std'

Fix MaterialX for VS2019 16.7 release

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Let clients be able to filter which metadata gets written to file during file save. At file write clients can give a predicate / filter function, to control this.
This is to avoid dumping out all VNN metadata to .mtlx files in LookdevX.

Support for filtering metadata during file save.

---

source/MaterialXRuntime/RtGeneric.cpp
source/MaterialXRuntime/RtGeneric.h

Fix possible crash bug if a generic prim schema (RtGeneric) is attached to a prim that was not created as a generic prim.

Fix issue with RtGeneric prim schema.

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtNodeGraph.cpp

- Fix crash when calling setNodeLayout on an empty nodegraph.
- Fix ignore saving of interfacename as metadata.

Fix crash when calling setNodeLayout on an empty nodegraph.

---

python/MaterialXTest/tests_to_html.py
resources/Materials/TestSuite/_options.mtlx
resources/Materials/TestSuite/pbrlib/bsdf/wedge_conductor.mtlx
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/MaterialNode.cpp
source/MaterialXCore/MaterialNode.h
source/MaterialXFormat/XmlIo.cpp
source/MaterialXTest/MaterialXCore/Observer.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.h
source/MaterialXTest/MaterialXRender/RenderUtil.cpp
source/PyMaterialX/PyMaterialXCore/PyMaterial.cpp

Update #632.
Update #966 
- Change the default to apply upgrades. The onus is on integrators to set a read option to not upgrade to the latest. 
- Note that this does not affect material node upgrade only the "latest" which is parameter->input upgrade.
- Prep / separate out material node upgrade. TBD where to put parameter->input upgrade.
- Fix up test display script to allow usage of on izip_longest (already in ILM 1.38 branch).
- Turn off wedge rendering by default.

Test and upgrade updates

---

source/MaterialXRuntime/Private/PvtApi.cpp
source/MaterialXRuntime/Private/PvtNameResolver.cpp
source/MaterialXRuntime/Private/PvtPrim.cpp
source/MaterialXRuntime/Private/PvtTypeDef.cpp
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtToken.h
source/MaterialXRuntime/RtTypeInfo.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

- Change storage type for generic metadata, string instead of token. Since we don't know what data might be stored in them using string is more safe.
- Removed assignment operator from string to RtToken. Since RtToken construction is expensive assignment/conversion from string to RtToken should be explicit.

Change generic metadata to use string instead of token

---

source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXTest/MaterialXCore/Document.cpp
source/PyMaterialX/PyMaterialXCore/PyDocument.cpp

Update #632 
- Allow for a downgrade path from uniform inputs to parameters.
- Change to always tag parameters as inputs on upgrade so they can be found.

Expose methods to allow parameter<->uniform input translation.

---

.travis.yml

- Remove release only and build release with debug always
- Use clang for a build per linux and mac (Xenial of linux)
- Use gcc for a build on linux (bionic + Python shared library)
- Javascript build on bionic.
Default push configs looks like this now.

Reduce number of builds on Travis for pushes

---

source/MaterialXRuntime/Private/PvtApi.cpp
source/MaterialXRuntime/Private/PvtApi.h
source/MaterialXRuntime/Private/PvtStage.cpp
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtNode.cpp
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXRuntime/RtStage.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

The concept of a "master prim" for instancing is only used for nodedef, and will probably never be used for anything other than nodedefs. So to clarify the API I have renamed this and removed the concept of "master prim" registration, now calling it nodedef registration instead.

Change "master prim" registration to nodedef registration.

---

.github/workflows/build_linux.yml
.github/workflows/build_mac.yml
.github/workflows/build_windows.yml

Update #1007 
- Split up to have 3 workflows, 1 for each platform.
- For how github actions does not allow individual builds to be restarted, only entire workflows, so the split is purely to make things more granular.

CI: create workflows per platform 

---

source/MaterialXContrib/MaterialXMaya/CreateMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXMaya/CreateMaterialXNodeCmd.h
source/MaterialXContrib/MaterialXMaya/MaterialXNode.cpp
source/MaterialXContrib/MaterialXMaya/MaterialXUtil.cpp
source/MaterialXContrib/MaterialXMaya/MaterialXUtil.h
source/MaterialXContrib/MaterialXMaya/MayaUtil.cpp
source/MaterialXContrib/MaterialXMaya/MayaUtil.h
source/MaterialXContrib/MaterialXMaya/Plugin.cpp
source/MaterialXContrib/MaterialXMaya/ReloadMaterialXLibrariesCmd.h
source/MaterialXContrib/MaterialXMaya/ReloadMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXMaya/ReloadMaterialXNodeCmd.h
source/MaterialXContrib/MaterialXMaya/ShadingNodeOverrides.cpp
source/MaterialXContrib/MaterialXMaya/ShadingNodeOverrides.h
source/MaterialXGenOgsXml/OgsFragment.cpp
source/MaterialXTest/MaterialXGenOgsFx/GenOgsFx.cpp
source/MaterialXTest/MaterialXGenOgsXml/GenOgsXml.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.cpp
source/MaterialXTest/MaterialXRenderOgsFx/RenderOgsFx.cpp

LOOKDEVX-349  Update for OGS XML Updates and Maya Plugin usage fixes
Update #460 
- Update to support 1.38 material nodes for OGSXML fragment generation and usage in Maya sample plugin.
- Port fix for units and update to include "adsk" library pathing into plugin.
- Update test configuration to write out ogsfx and ogsxml source output

1.38 Update for OGS XML Updates and Maya Plugin usage fixes

---

.github/workflows/build_linux.yml
.github/workflows/build_mac.yml

Update #1007 
Update based on changes in MaterialX 1.38:
https://github.com/materialx/MaterialX/commit/45324365ed48681ab427bc90f2eae2992a84a49c
Addresses deprecation of set-env
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Update env commands in GitHub Actions

---

source/MaterialXCore/MaterialNode.cpp
source/MaterialXCore/MaterialNode.h
source/MaterialXGenShader/ShaderTranslator.cpp
source/MaterialXTest/MaterialXGenShader/GenShader.cpp
source/PyMaterialX/PyMaterialXCore/PyMaterial.cpp

Update #1023 
Add equivalent to ShaderRef::gerReferencedOutputs() via new utility getConnnectedOutputs() in MaterialNode.
This should fix incorrect upgrade inside ShaderTranslator to find upstream graphs properly now.

Fix ShaderTranslator upstream output search logic 

---

source/MaterialXGenShader/ShaderTranslator.cpp

Add handling for physical units and colorspace tags that were not getting passed through by the translation traversal.

Fix ShaderTranslator propagation of units and colorspace tags

---

libraries/translation/standard_surface_to_UsdPreviewSurface.mtlx
source/MaterialXCore/MaterialNode.cpp
source/MaterialXCore/MaterialNode.h
source/MaterialXGenShader/ShaderTranslator.cpp
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXTest/MaterialXGenShader/GenShader.cpp

Update #921 
- Minor patches to re-initialize cached state after each material/shader baked or translated.
- Update translate test to perform multiple translates. Bake test already performs multiple bakes per document.
- Fix "optimize" constants to skip any prep work for optimization to not leave state cached image state incorrect if turned off.

Cleanup TextureBaker and Translator (including re-initialization)

---

libraries/bxdf/usd_preview_surface.mtlx

We appear to be double counting Fresnel, with conductors for UsdPreviewSurface, in the metallic-roughness workflow

Fix UsdPreviewSurface conductor Fresnel inputs.

---

resources/Materials/TestSuite/pbrlib/surfaceshader/mapped_surfaceshader.mtlx
source/MaterialXCore/Document.cpp
source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/MaterialXGenGlsl/GlslSyntax.cpp
source/MaterialXGenMdl/MdlSyntax.cpp
source/MaterialXGenShader/Util.cpp
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h

Update #974 
- Separate out utility to change the category of a child element to Core Util: 
- ElementPtr changeChildCategory(ElementPtr parent, ElementPtr origChild, const string& category);
- Fix TextureBaker::bakeAllMaterials() to use the generator created at class initialization as unit system setup is done on that generator.
- Fix enum parsing during shader generation. Was not handling cases where there were any spaces between comma separated lists. e.g. ("tangent, object") would not parse "object" as a valid enum.

Category changing utility + TextureBaker fixes.

---

source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h
source/MaterialXTest/MaterialXGenShader/GenShader.cpp

Disable Graphflatten as part of BakeShaderInputs since this corrupts the nodes that are dot connected.
Add a simple stringstream to capture baking log instead of writing to std::cerr, std::cout

Updates to TextureBaker

---

source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h

The baker by default uses the Code Search path based on the Installed. 
Add an API to allow this to be configurable.

Add setCodeSearchPath to Baker Configuration

---

source/MaterialXContrib/MaterialXMaya/Plugin.cpp
source/MaterialXContrib/MaterialXMaya/ShadingNodeOverrides.cpp

Update #1044 
- Add "targets" to contrib plugin so targetdefs are found.
- Also add in "adsk" so this library is found.
- Fix up texture path searching to resolve filenames properly and also look for default names from the nodedef if 
not specified on the node itself.
- All nodes in adsk_shaders.mtlx test file load and render correctly:
https://github.com/autodesk-forks/MaterialX/blob/adsk_contrib/dev/resources/Materials/TestSuite/adsklib/adsk_shaders.mtlx
Sample using "adsk" color correct as a texture node:
Sample using "adsk" shaders which require nodedef textures. 4 Maya shaders and 1 Maya texture (connected to to a Maya Phong)

LOOKDEVX-374 : Targetdef update for contrib plugin

---

source/MaterialXCore/Document.cpp

Update #632 
Set all non-filename and non-string parameters as non-uniform inputs as part of upgrade.

Make v1.38 upgrade path only mark filename and string parameters as uniforms.

---

source/MaterialXRenderGlsl/GlslRenderer.cpp

GlslRenderer. This is a temporary fix for now, we will need to discuss
the correct workaround in the future.

LOOKDEVX-402 | Putting back the make current call when unbinding geometry in the

---

source/MaterialXCore/Document.cpp

Update #460 
Remove keeping the version at 1.37 when an upgrade occurs for consistency.

Set upgrade version to 1.38 instead of 1.37 

---

resources/Materials/TestSuite/stdlib/nodegraph_inputs/surfacematerial_nodegraph_to_surfaceshader.mtlx
source/MaterialXCore/Material.cpp

Update #385 
Update getShaderNodes() utility to find shaders which are connected to surfacematerial which is in a nodegraph.
Use getConnectedNodes() which handles these configurations properly now instead of directly trying to access the connected
node.

1.38 : Support nodegraph connections for material to shader search

---

source/MaterialXFormat/Util.cpp

Don't append a search path if the filename to consider is empty.

Fix adding search path to empty filenames during when "flattening"

---

source/MaterialXRender/ShaderRenderer.cpp
source/MaterialXRender/ShaderRenderer.h
source/MaterialXRenderGlsl/GlslRenderer.cpp
source/MaterialXRenderGlsl/GlslRenderer.h
source/MaterialXRenderGlsl/TextureBaker.cpp
source/PyMaterialX/PyMaterialXRender/PyShaderRenderer.cpp
source/PyMaterialX/PyMaterialXRenderGlsl/PyGlslRenderer.cpp

Update #921 
Load images required for shader and return list of images loaded
`virtual ImageVec getImageList (const ShaderPtr& shader);`
This inspects the Shader and loads images required by the shader.
The ImageVec contains the list of Images loaded.

ShaderRenderer API to getImageList

---

resources/Materials/TestSuite/stdlib/upgrade/1_38_parameter_to_input.mtlx
source/MaterialXView/CMakeLists.txt
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

Fixed #1126 
- Add option in MaterialXView to output Arnold target OSL code via the "A" key. e.g.
- Add in test graph for issue.
Test Results:
[feb_23_2021_tests.pdf](https://github.com/autodesk-forks/MaterialX/files/6030859/feb_23_2021_tests.pdf)

Add additional testing for Arnold OSL output

---

source/MaterialXGenShader/Util.cpp

Update #1130.
This changelist updates the transparency detection heuristic in MaterialXGenShader/Util.cpp for v1.38 shader nodes.  There's still plenty of room for future improvement, but this implementation generates correct results for all examples in the MaterialX repository.

Merge transparency update

---

CMakeLists.txt
source/MaterialXCore/Document.cpp
source/MaterialXTest/MaterialXGenArnold/GenArnold.cpp

Update #1150 
Add in special Arnold "context" support when upgrading "shaderrefs". 
Use as the type to create instead of checing the regular node, nodedef attributes.
This will only be enabled for builds with the build flag `MATERIALX_BUILD_GEN_ARNOLD` set.
Test case added wit this test as input:
```
<materialx version="1.36">
<material name="test_material">
<shaderref name="simple_srf1" node="noise" context="surfaceshader">
<bindinput name="octaves" type="int" value="12" />
<bindinput name="distortion" type="float" value="6" />
<bindinput name="lacunarity" type="float" value="2" />
<bindinput name="amplitude" type="float" value="1" />
<bindinput name="color1" type="color3" value="1, 1, 0" />
<bindinput name="color2" type="color3" value="0.9, 0.1, 0" />
</shaderref> …
```

Support legacy Arnold "context" hint on shaderref upgrade

---

source/MaterialXGenMdl/MdlShaderGenerator.cpp
source/MaterialXGenMdl/MdlSyntax.cpp

Fixes #1145 
- Fixes erroneous generation of a texture_2d() reference with "/" as an argument when no value is specified such as for input arguments.
Fixes #1146
- Remove workaround of making texture_2d() lookups inlined.
The corrected input looks like this;
```
mdl 1.6;
using mx = materialx;
import ::df::*;
import ::base::*;
import ::math::*;
import ::state::*;
import ::anno::*;
import ::tex::*;
import ::mx::swizzle::*;
import ::mx::cm::*;
using ::mx::core import *;
using ::mx::stdlib import *;
using ::mx::pbrlib import *;
using ::mx::sampling import *;
float NG_tiledimage_float
(
uniform texture_2d file = texture_2d(),
float default1 = 0,
float2 texcoord = float2(0.0),
float2 uvtiling = float2(1, 1),
float2 uvoffset = float2(0, 0),
float2 realworldimagesize = float2(1, 1),
float2 …
```

MDL texture lookup code generation fixes.

---

libraries/adsk/adsklib/adsklib_defs.mtlx
libraries/adsk/adsklib/adsklib_ng.mtlx
source/MaterialXContrib/libraries/adsk/adsklib/adsklib_tr_ng.mtlx

The image samples defaults to "periodic". Expose this into adsk:bitmap, adsk:normal_map and adsk:height_map for user configuration.

Add u/v addressmode intefaces to adsk image nodes

---

source/MaterialXRuntime/Private/PvtPort.cpp
source/MaterialXRuntime/Private/PvtPort.h
source/MaterialXRuntime/RtConnectableApi.cpp
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtPort.cpp
source/MaterialXRuntime/RtPort.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Update #1159
Add in support for `<token>` as a runtime "input" which is marked as a token.
Example nodegraph with token called `mytoken` which is marked as non-visible.
```
<materialx version="1.38">
<nodegraph name="Tokenized_graph" xpos="1044.25" ypos="852.077" >
<token name="mytoken" type="color3" value="1, 1, 1" uivisible="false" uiname="My Token"/>
<input name="value" type="color3" value="0, 0, 0" uivisible="false"/>
<constant name="constant" type="color3" xpos="-136.498" ypos="-120.44">
<input name="value" type="color3" interfacename="value" value="0, 0, 0" uivisible="true" />
</constant>
<output name="out" type="color3" nodename="constant" />
</nodegraph>
<collection name="defaultCollection" includecollection="" includegeom="/*" xpos="315" ypos="229" /> …
```

Runtime token support

---

source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Fix up Runtime nodedef read to indicate that "uivisible" is a boolean type.
Otherwise it defaults to a string type and will throw an exception when trying to access it as a boolean.

Fix read for Runtime nodedef to set "uivisible" as boolean

---

source/MaterialXRender/Util.cpp
source/MaterialXRender/Util.h
source/MaterialXView/Main.cpp
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

Update #1166
Use a shader versus a hardware OpenGL sRGB buffer which is not supported in some cases.
The shader created for this is simple and can be extended if needed.
The scale+offsets (multiply+add) are there to perform a possible vertical flip on any input image.
The image for the viewer is taken from the output framebuffer.
To compensate for the background being transformed, the background color is set to un-gamma corrected color.

Allow output gamma shader for MaterialXView

---

source/MaterialXGenShader/UnitSystem.cpp
source/MaterialXGenShader/UnitSystem.h
source/MaterialXView/Viewer.cpp

Update #1167 
Fix to check up the targetdef derivation hierarchy for a matching implementation for units.

Fix unit code generation support for Arnold code generator

---

source/MaterialXRuntime/Library.h
source/MaterialXRuntime/Private/PvtObject.h
source/MaterialXRuntime/RtType.cpp
source/MaterialXRuntime/RtType.h
source/MaterialXRuntime/RtTypeDef.cpp
source/MaterialXRuntime/RtTypeDef.h
source/MaterialXRuntime/RtValue.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Add type checks to find issues with value types mismatching. Only enabled in debug builds to avoid a performance cost in release builds, but bugs can be found in debug builds.

Add type checks for RtTypedValue access in debug builds.

---

source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h

The code checking for valid namespace is moved from the Compound publishing dialog to the MaterialX Utilities.

Add utility to check for valid MaterialX namespace.

---

source/JsMaterialX/JsMaterialXCore/JsTraversal.js
source/JsMaterialX/initMaterialX.js
source/JsMaterialX/test/document.spec.js
source/JsMaterialX/test/traverseGraph.spec.js

This PR removes the implicit exception handling (i.e. resolving exception pointers to messages) in the JS bindings. This is another step on the way to remove the JS boilerplate code. Exceptions will now have to be resolved at the application level if the error message is of interest.
FYI @sdunkel @kohakukun @muenstc

JS Bindings: Remove implicit exception wrapping

---

.github/workflows/build_mac.yml

`lipo MaterialXView -detailed_info `
```
Fat header in: MaterialXView
fat_magic 0xcafebabe
nfat_arch 2
architecture x86_64
cputype CPU_TYPE_X86_64
cpusubtype CPU_SUBTYPE_X86_64_ALL
capabilities 0x0
offset 16384
size 47879072
align 2^14 (16384)
architecture arm64
cputype CPU_TYPE_ARM64
cpusubtype CPU_SUBTYPE_ARM64_ALL
capabilities 0x0
offset 47906816
size 48289248
align 2^15 (32768)
```

Enable arm64 for macOS Xcode 12 build

---

source/JsMaterialX/JsMaterialXView/.gitignore
source/JsMaterialX/JsMaterialXView/index.html
source/JsMaterialX/JsMaterialXView/package.json
source/JsMaterialX/JsMaterialXView/shader-frag.glsl
source/JsMaterialX/JsMaterialXView/shader-vert.glsl
source/JsMaterialX/JsMaterialXView/src/index.js
source/JsMaterialX/JsMaterialXView/webpack.config.js

This is a minimal app to render the shaderball with custom shaders. Once the WebGL Shader Generation is working we can easily hook it up to the app to visualize MaterialX materials.
Update materialx#344, #1184

Initial ThreeJS viewing app

---

.github/workflows/main.yml
python/Scripts/generateShader.py
source/PyMaterialX/PyMaterialXGenShader/PyUtil.cpp

Interface was trying to pass by reference an argument. 
Instead write a C++ wrapper to call the C++ interace and return a value. This makes it so the C++ API does not need to change.
Added CI testing.
e.g. testing output:
```
python python/Scripts/generateShader.py resources/Materials/Examples/StandardSurface/standard_surface_look_brass_tiled.mtlx --path "." --outputPath "build_public_rel/generate/" --target "glsl"
python python/Scripts/generateShader.py resources/Materials/Examples/StandardSurface/standard_surface_look_brass_tiled.mtlx --path "." --outputPath "build_public_rel/generate/" --target "osl"
python python/Scripts/generateShader.py resources/Materials/Examples/StandardSurface/standard_surface_look_brass_tiled.mtlx --path "." --outputPath "build_public_rel/generate/" --target …
```

Fix findRenderableElements() Python wrapper.

---

source/MaterialXTest/CMakeLists.txt
source/MaterialXView/CMakeLists.txt

Tests used to be located in `build/source/MaterialXTest`
But since the test executable has now moved to `build/bin` the tests would fail to find config files and just skip.
This moves all the test material to `build/bin` so test can run again.

Fix unit test rig

---

source/MaterialXGenEssl/EsslShaderGenerator.cpp
source/MaterialXGenEssl/EsslShaderGenerator.h
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenGlsl/GlslShaderGenerator.h

Resource bindings via a location qualifier are not supported on Webgl.

Throw if EsslShaderGenerator has access to a resource binding context

---

source/MaterialXTest/MaterialXRender/RenderUtil.cpp

Update #1245.
Patch to not write out baked document files with extension "mtlx" as these will be picked up later for rendering.
Use "xml" instead.

Stop rendering of baked documents.

---

documents/DeveloperGuide/CodeExamples.md
source/JsMaterialX/README.md
source/JsMaterialX/test/codeExamples.spec.js

This PR consolidates the setup and build instructions in the readme by
- delegating specific steps to original tool documentation pages (e.g. emscripten, Docker)
- adding more details on using the emsdk directly
- explaining alternatives to using the emsdk directly
- clarifying usage of the official Docker image
Furthermore, once of the examples in `codeExamples.md` is updated. The other ones still need to changed, once we know how they should look like (C++ and Python and outdated atm).
A note for reviewers: It might make sense to look at the updated document separately to read the instructions in one piece, instead of trying to follow them in the diff view.
The different sections of this readme will be moved to their official locations in a follow-up PR.
Update #1184

JS Bindings: Improve setup and build instructions

---

source/JsMaterialX/JsMaterialXFormat/JsXmlExport.cpp
source/JsMaterialX/JsMaterialXFormat/JsXmlIo.cpp
source/JsMaterialX/JsMaterialXFormat/post.js
source/JsMaterialX/README.md
source/JsMaterialX/test/xmlExport.spec.js
source/JsMaterialX/test/xmlIo.spec.js

This PR enables writing documents to files. In the browser, the file will be downloaded automatically.
Update #1184

JsBindings: Add support for writing documents to files

---

.github/workflows/build_wasm.yml
source/JsMaterialX/JsMaterialXView/src/index.js

Use relative path instead of absolute to fix issue when loading draco loader

fix: JSMaterialXView draco path

---

source/MaterialXGenShader/Nodes/HwImageNode.cpp
source/MaterialXGenShader/Nodes/HwImageNode.h

Update #1144
Expose hardcoded UDIM transform names.
Currently used for texture atlas lookup but can be used for texture array lookup when that is supported.

Expose names of transforms for UDIM texture atlases 

---

source/JsMaterialX/README.md

* Update module loading section
* Move shader generation usage to the appropriate place

JS Bindings: Clean up readme

---

source/MaterialXGenShader/Util.cpp

Update #1280
Ignore "adjustment nodes" and assume they do not affect the transparency heuristic.
This handles the luminance connection in std surface.

Ignore luminance connection in std surface for transparency heuristic.

---

source/MaterialXTest/MaterialXGenShader/GenShader.cpp

Update #1280
Add in C++ transparency heuristic tests for all cases except  testing if upstream adjustment graphs which is considered transparent. Final heuristic to be worked out.

Add in transparency sanity checking tests cases 

---

source/MaterialXView/Viewer.cpp

Fix regression dues to not considering "libraries" folder as root for texture paths for definitions.

Fix image pathing regression in viewer

---

source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Add in missing search path. Ordering of tests may differ resulting in this test failing due to lack of path.

Fix non-deterministic Runtime test

---

source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/MaterialXTest/MaterialXCore/Unit.cpp

Move the function building the base compound name into MaterialX utils and add a basic test case.

t-rusel/LOOKDEVX-484/add prefernces option

---

libraries/pbrlib/genglsl/lib/mx_math.glsl
source/MaterialXGenGlsl/GlslResourceBindingContext.cpp
source/MaterialXGenGlsl/GlslResourceBindingContext.h
source/MaterialXGenGlsl/GlslSyntax.cpp
source/MaterialXTest/MaterialXGenGlsl/GenGlsl.cpp

Addresses an issue that we need to generate Vulkan semantics to generate Vulkan-compliant code. Also treat 'sampler' as a reserved word.
Thanks to Jerran for the changes.
```
100% tests passed, 0 tests failed out of 105
Total Test time (real) = 363.45 sec
```

GlslResourceBindingContext option to separate binding locations 

---

source/MaterialXView/Viewer.cpp

Fix a typo in MaterialXView. 
Remove use of _genContextEssl since it is not used for Rendering but only for CodeGen.

Fix STL crash in Debug and remove ESSLContext config

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtStage.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

This is the current logic. Rt may or may not have namespaced nodedefs. Ones created by publishing via Rt and ones imported via core will have qualified names. On write to MTLX always strip out any qualifier on a nodedef if it's already namespaced.

Fix node graph and node definition reference when publishing compounds.

---

source/MaterialXRuntime/Private/PvtPrim.cpp
source/MaterialXRuntime/RtStage.cpp

Numbers such as "1.0" were being directly embedded into new definition and nodegraph names
when create a new nodedef via the runtime.
Add in valid name checking on nodedef creation and for general unique name utility which is used when renaming
a node (nodegraph in this case).

Fix regression of creating invalid name when create new definitions

---

.github/workflows/main.yml

Update #1184 
Merge generate test in with regular "python" test.
Also run on all runs as it has very small cost. (i.e. no more `test_generate` workflow flag.

Simplify test workflow

---

.github/workflows/main.yml
resources/Materials/TestSuite/stdlib/materials/material_node_discovery.mtlx
source/JsMaterialX/JsMaterialXCore/JsMaterial.cpp
source/MaterialXCore/Material.cpp
source/MaterialXCore/Material.h
source/MaterialXTest/MaterialXCore/Material.cpp
source/PyMaterialX/PyMaterialXCore/PyMaterial.cpp

- discovery returns any node or nodegraph which has a one or more `material` outputs
- Works on a nodegraph, materialassign, or document as the element to test from.
- Document level . It ignores implementation nodegraphs.
- Nodegraph discovery does not check if the graph is an implementation or not.
Refer to images in:
https://github.com/materialx/MaterialX/issues/737
for graphical view of configurations tested.
*Material nodes discovered which are referenced by `materialassigns`*
- Found material node: top_level_material_assigned
- Found material node: top_level_material_in_graph_assigned/surfacematerial1
- Found material node: top_level_material_def_assigned
*Material nodes discover which are within a nodegraph*
- Found output material node: …

MATX-303 : Material Node discovery 

---

.github/workflows/main.yml
libraries/pbrlib/genglsl/lib/mx_microfacet_specular.glsl
python/Scripts/generateshader.py
source/PyMaterialX/PyMaterialXGenShader/PyGenContext.cpp

For Vulkan-compliant codegen use 'tex_sampler' as variable name instead of reserved word 'sampler' as consistent with earlier changes in other shader libs.
Add a test to generate and validate Vulkan-compliant GLSL.
Fix bug that wasn't including codevalidator arguments as part of the codevalidator command.

MATX-328 : Avoid reserved word 'sampler' for Vulkan-compliant codegen in glsl libs

---

source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h

This is needed for edit operations on an Element hierarchy. `removeChild(by string name)` already exists but there was no way to add an existing element as child of another element.

Added method Element::addChild (by shared pointer)

---

python/MaterialXTest/tests_to_html.py

Was adding source and dest lists incorrectly, producing source on one row and dest on another.
Also cleaned up to use source to determine dest file name by replacing language.
Fix to allow only one language to be shown again.

MATX-363 : Fix render unit test html generator 

---

resources/Materials/TestSuite/Utilities/sphere.ma

The uvs on this are **not** the default ones created by Maya as the (0,V) line for some
reason does not align with the (0, Y, 0) axis. Also the geometry has been rotated so the (0,V) line is along the -Z
axis. This is the agreed upon reference rendering convention and is also followed by OSL's `testrender` reference renderer.

Check in Maya "ground-truth" reference sphere.

---

libraries/adsk/adsklib/adsklib_defs.mtlx
libraries/adsk/adsklib/adsklib_ng.mtlx

Current mtlx sdk only support color3 adsk:bitmap, for transparent decal image, it has 4 channels as png. We need to support color4.

Add adsk:bitmap color4 support to MaterialX SDK

---

libraries/adsk/adsklib/adsklib_defs.mtlx

The adsk:bitmap node always renders as "periodic" no matter u/vaddressmode set as. 
After this pr the expected result in MaterialXView is as shown below (unit is inch).

fix UV address mode of MaterialX SDK adsk:bitmap node

---

libraries/adsk/adsklib/adsklib_defs.mtlx
libraries/adsk/adsklib/adsklib_ng.mtlx

Add a simple uv_index input for adsk:bitmap, adsk:normal_map, adsk:height_map. This parameter enable client to set uv index number and another consumer side could parse and use this value. This solution is used to support multiple UV for 3ds Max glTF exprot workflow.

Support multiple UV

---

libraries/adsk/adsklib/adsklib_ng.mtlx

To solve the texture shearing issue https://github.com/AcademySoftwareFoundation/MaterialX/issues/1021, we have added a new input "operationorder" for `place2d `node in this pr https://github.com/AcademySoftwareFoundation/MaterialX/pull/1027.
Here for all adsk bitmap nodes, we change the "operationorder" value to 1 so that they won't be sheared any more.

fix texture shearing problem for adsk bitmap nodes

---

libraries/adsk/adsklib/genglsl/adsklib_genglsl_impl.mtlx
libraries/adsk/adsklib/genosl/adsklib_genosl_impl.mtlx

Change the file path in  `implementation` element to point directly to the glsl/osl file

Fix "libraries" reference in adsklib nodedefs

---

libraries/adsk/adsklib/adsklib_defs.mtlx

adsk:ND_adsk_height_map was not categorized as Texture node, this was causing Hydra/Storm to ignore the associates samplers with this node.

Add correct category for adsk:ND_adsk_height_map node

---

contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Due to a bug in graph editor, a lot of inputs had connections to an interfacename and a value, when  only the interfacename was needed.
This is fixed in future graph editor builds, but probably only for new created inputs, so a clean slate is necessary for safety.
The graphs were working in Viewer, but causing issues in LookdevX. LookdevX now handles this case if we face it again in the future.

Fix redundant values

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx

Seemed like units defaulted to meters also for angle units. Adding explicit defaults so that conversion does not  try to convert meters to degrees.

Adding explicit default units

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx

Specifying both "unittype" and "unit" in nodedefs breaks something, and the conversion between units does not happen when switching them in Viewer.
This change remove "units" from nodedefs inputs of type "distance".
Note that "unit" remains for angles. Removing it causes an error (likely a bug) at load time. "Unrecognized destination unit: meter"
Seems like materialX tries to convert degrees to meters.
While things seem to be still a bit buggy for angles, this seem to currently work at least for distances. Viewer doesn't not allow to change the angle unit, so it can't be tested in that environment. It's likely that angle will fail as distances were failing when unit was present.

Remove unit settings from distance nodedefs inputs

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Adding **Marble** and **Speckle** nodedefs and nodegraphs. This includes a small utility node called `util_specklenoise`. Note that this is classified as an utility node rather than a new noise because it's just an existing noise with some multiply and range adjustments that is re-used multiple times in Marble and Speckle. It has no real use outside of that.
Couple of more fixes
1) The `legacy_noise` procedural transform order has changed. Now rotate is execute before translate. (small node connection changes from line 440 to 510 in nodegraph file)
2) Small formatting/space changes to `legacy_noise` nodedef. (line 69 to 80)

Marble and Speckle procedurals plus minor fixes

---

contrib/adsk/libraries/adsklib/adsk_colorcorrect.mtlx
contrib/adsk/libraries/adsklib/adsklib_ng.mtlx
contrib/adsk/libraries/adsklib/adsklib_tr_ng.mtlx

This fix was already done for the protein graphs, after an issue with LookdevX discovered it.
The MaterialX team made some changes to avoid double "value" and "interfacename" (or "nodename")  to the Graph Editor and added a sanity check on load.
Loading the Prism documents in 1.39 now throws a bunch of warnings. This fix removes all the extra "value" attributes and no warnings are generated any more.

Removing extra value attributes form nodgraphs inputs

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Legacy Tiles added.
Supports all features from the Protein Tiles except the Column Modifier, which works only under specific conditions and mostly corrupts the pattern. I left it out. It's very unlikely anybody used it, ever.
Also fixing a couple of uninitialized inputs on Fractal Noise.

Adding Legacy Tiles procedural

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

The previous Checker was done in Graph Editor. This version imported Checker into LookdevX and re-authored it similarly to the other more recent procedurals.
The shader uses the stdlib Checker, which does not have a Rotation option. The result was that Rotation was processed before Translation, which is the opposite of OGS. To address this, the stdlib Checker offset is not used any more, and the UV are translated and rotated before being sent to Checker.
Color outside of the pattern when not fully tiled is now black to match other procedurals.
Note that there are small inconsistencies in inputs and formats that will be addressed in bulk affecting multiple nodes at a later stage. Jiras already exist for that.

Replacement of Checker procedural

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Updated version of Noise Procedural, fully 3D.
All features matching original OGS except Phase, which does not exist in the stdlib noise functions or the custom noise functions (materialx graphs) for Turbulence and Fractal with fractional levels. Adding Phase would require a complete rewrite of all base functions from scratch.
Added a smoothstep transition option that could be useful when threshold are used.
Also fixed two small UI range settings in the turbulence noises defs.

Replacement for Noise Procedural

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

This is the protein Gradient, supporting all the gradient types and noise settings.
There is a base "float" version and a simple but usable "color 3" version that interpolates between 2 colors.
The Color3 version is not a Protein requirement, but the Ramp we need to match Protein is still TBD.
Something to deal with Ramp will be added later when updating to 1.39, and even then we will have a sub-par user experience to define a ramp properly. This is a discussion for another day.

Adding Legacy Gradient procedural

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

As the Blur node from MaterialX does not blur much, I implemented the original OGS math based blur, which is likely more efficient anyway.
Removed the Blur node
Added a whole graph section to do the blur (called Soften in OGS terms) Added an option to compensate for the stretching of the blur

Checker Blur implementation

---

contrib/adsk/libraries/adsklib/adsk_colorcorrect.mtlx

Removing swizzle nodes by replacing the ones extracting "rgb" with a Convert color4 to color3, and the ones extracting "a" with an Extract using index 3.
The diff is confusing to read, but the changes are very simple. Verified also by opening it back in LookdevX and Graph Editor, the connections are sound and the nodes types, inputs, and outputs are correct.
@JGamache-autodesk

Swizzle removal

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx

Waves and Wood were missing the units attribute because I was not sure if they were supposed to be in units or not.
In CMUI (Inventor) they do not have units, but that seems odd as that would make them inconsistent if projects units were changed. Tests show that changing the units do not change the procedural size.
After experimenting a bit I'm sure units are needed even if not used in the current CMUI.
For Waves, the units seem to be cm.
Also, tests shows that Waves is the only procedural working in World space. The default has been updated too.
More testing and refinements might be necessary once we can run legacy and graphs side by side.

Adding missing units attributes

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

After submitting each procedural separately, this update unifies the defs format.
Details:
- Added "_color3" suffix to 4 graphs that were missing it (and same changes in nodegraph file)
- Added all missing uinames, based mostly on CMUI naming
- Removed xpos/ypos from older defs created in Graph Editor
- All uifolder removed, we might use them one day, but for now they are just cluttering
- Moved attributes around to try to make them in the same or close to same order
- Added enum for Gradient Type (float and color3)
- Some unit="degree" removed. Works both ways, and we still have issues on that, but for now I unified all to no unit attribute for 3D angles (but stays for 2D rotation)
- All versions are set to "0.1" for now. We might decide for a real number one day.
- Utility nodes (the …

Protein Procedurals Defs cleanup

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

1) Changing a bunch of separate inputs to vectors (offsets 2d and 3d, rotation 3d). Unified names to match Prism:
- realworld_offset (vector2 or vector3)
- realworld_scale (vector2)
- rotation_angle (float or vector3)
2) Change inputs secting behaviours to be integer and adding enum and enumvalues attributes. This affects Noise and Gradient Types in one or more places. Note that for now the integer input is converted to float inside the graph to use float math. This will be replaced in the future with integer math now that we have switched to MaterialX 1.39, where it's finally available.
3) Set all texcoord and position inputs to uivisible="false" (except util nodes)
4) A few inputs were renamed to remove underscore (noise and marble) That's ok for now, and make most inputs consistent, …

Coordinates inputs revision, enums, and other

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Unify the procedurals input names format to use underscores like Prism and Protein materials.
Most changes in the nodedefs are simply underscores added to separate words. In a very few cases, the rename was more drastic to clarify the input meaning.
The nodegraphs reflects the changes to the nodedefs, but in some cases a few nodes inside had to be renamed because they had the same name as the new inputs, and that is not allowed.
Utils nodes, not meant to be used separately, are not part of this renaming.

input renames

---

.github/workflows/adsk_tag.yaml

This GitHub Action will read the latest tag from `AcademySoftwareFoundation/MaterialX` and create a new one in `autodesk-forks` with the format `<upstream_tag>.<3lettermonth>_<YYYY>.dev_adsk`

Add manually triggered GitHub Action to create the latest adsk tag

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx
contrib/adsk/resources/Materials/TestSuite/adsklib/legacy/test_mat_legacy_ceramic.mtlx
contrib/adsk/resources/Materials/TestSuite/adsklib/legacy/test_mat_legacy_glazing.mtlx
contrib/adsk/resources/Materials/TestSuite/adsklib/legacy/test_mat_legacy_metal.mtlx

Revision of Ceramic, Mirror, Metal, Glazing Protein materials as part of the phase 3 of the graphs work.
Most changes are about input names, new inputs for normals, switch enum inputs from float to integer (and associated NG changes), swizzle nodes removal, and other graphs optimizations and documentation (backdrops added).
Also changed are nodedef inputs using defaultgeomprop, where the value attribute was removed if present. This was done for all the materials, not just the ones listed above.
These graphs are now authored in LookdevX, so a lot of changes in the diff are formatting and node coordinates.
The changes to the inputs will break the materials converter if this version of MaterialX goes into USD.

Protein Phase 3 - Ceramic Mirror Metal Glazing

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Few minor changes:
- Renamed an input and added an invert node to change the roughness into a glossiness input to match the Protein schema.
- Deleted a few nodes that were parked on the side, unconnected, part of the old noise that is now an external input.
- Fixed a node names typo "coatr"->"coat"
- Some nodes moved around (xpos/ypos changes)

Metallicpaint change from roughness to glossiness

---

.github/workflows/main.yml

In `autodesk-forks`, the `gh-pages` branch is protected so it can't be updated by the JS workflow.

Disable 'Deploy Web Viewer' job

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx
contrib/adsk/resources/Materials/TestSuite/adsklib/legacy/test_tex_legacy_knurl.mtlx

Adding nodedef and nodegraph for Legacy Knurl.
This implements a generic knurl that is a superset, usable standalone, of the knurl used as a Metal pattern. The original knurl in RapidRT was not usable standalone. This solution is different and has more features, making it a worthwhile extra procedural to add to the library.
A coupe of extra fixes are included
- defaults for a couple of size parameters were incorrectly set to 0,0 after changing them to vector2.
- A converter node from LookdevX was removed. It was unconnected, and it might be recreated if that graph is re-exported. I'll try to keep an eye on it. No biggie if it's there anyway.

Adding legacy knurl
