autodesk-forks/MaterialX

source/MaterialXTest/ShaderValid.cpp
source/MaterialXView/CMakeLists.txt
source/MaterialXView/OpenGL/GLCocoaWrappers.h
source/MaterialXView/OpenGL/GLCocoaWrappers.m
source/MaterialXView/OpenGL/GLUtilityContext.cpp
source/MaterialXView/Window/HardwarePlatform.h
source/MaterialXView/Window/SimpleWindow_mac.cpp
source/MaterialXView/Window/WindowCocoaWrappers.m
source/MaterialXView/Window/WindowWrapper.cpp

- Minor cleanup of interface calls to Cocoa
- Clean up seperation of GL and non-GL Cocoa wrappers
- Set up build dependencies

Update MaterialXView for Mac support

---

source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXTest/Document.cpp

* New Element::getElementByPath function.
* Applied code review feedback.
* Applied code review feedback.
* Applied code review feedback.
* Applied Jonathan Stone's feedback.
* Applied additional feedback from Jonathan Stone.
* Applied additional feedback from Jonathan Stone.

New Element::getElementByPath function. (#21)

---

source/MaterialXShaderGen/HwShaderGenerator.cpp
source/MaterialXShaderGen/SgNode.cpp
source/MaterialXTest/ShaderGen.cpp

Use the improved NodeDef::getImplementation in MaterialX API instead of our own code for this

Use the improved NodeDef::getImplementation

---

source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.h
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightGlsl.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/SurfaceShaderGlsl.cpp

Fixed bug with missing light direction variable in LightGlsl implementation.

Fixed bug with missing light direction variable.

---

source/MaterialXCore/Value.cpp

Extracting this change shadergen branch where the build will fail with that build config.

Small modification to avoid template build error.

---

source/MaterialXCore/Value.cpp

Small modification to avoid template build error.

Template build fix

---

documents/Examples/SubGraphs.mtlx
source/MaterialXShaderGen/SgNode.cpp
source/MaterialXShaderGen/SgNode.h
source/MaterialXShaderGen/Shader.cpp
source/MaterialXShaderGen/ShaderGenerators/Common/Compound.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/LightCompoundGlsl.cpp
source/MaterialXShaderGen/ShaderGenerators/Osl/OslSyntax.cpp
source/MaterialXTest/Node.cpp
source/MaterialXTest/ShaderGen.cpp

- Fixed bugs and improved creation of shader graph interfaces from nodedefs
- Fixed bugs with connecting internal nodes to the shader graph interface when requested
- Removed use of the deprecated "publicname" attribute
- Unification of code, removing code duplications, etc.

Improved shader graph contruction.

---

source/MaterialXCore/Types.cpp
source/MaterialXCore/Types.h
source/MaterialXCore/Value.cpp
source/MaterialXTest/Main.cpp
source/MaterialXTest/Types.cpp
source/PyMaterialX/PyTypes.cpp

Matrix additions:
- translate/rotate/scale/transpose
- extract to string
- equivalence
Vector additions:
- magnitude
- normalize
CTest:
- Make routing of output to debugger conditional on if using debugger to run program. Otherwise route to cout (default)

Vector / Matrix update

---

source/MaterialXShaderGen/SgNode.cpp
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxSyntax.cpp
source/MaterialXTest/ShaderGen.cpp

Also fix for a build warning in VS2017.

Fixed the regression bug introduced in previous commits. 

---

documents/Libraries/sxpbrlib/sx-glsl/ogsfx/lighting_functions.glsl
documents/Libraries/sxpbrlib/sx-glsl/ogsfx/lighting_uniforms.glsl
source/MaterialXShaderGen/ShaderGenerators/Glsl/OgsFx/OgsFxShaderGenerator.cpp

Change view position semantic to WorldCameraPosition and add light

---

documents/Libraries/sxpbrlib/sxpbrlib_defs.mtlx
documents/Libraries/sxpbrlib/sxpbrlib_ng.mtlx
source/MaterialXShaderGen/ShaderGenerators/Glsl/GlslShaderGenerator.cpp
source/MaterialXTest/ShaderGen.cpp

Changed the name of Standard Surface to "standard_surface" to follow the convention used in Arnold.

Standard surface cleanup

---

source/MaterialXShaderGen/HwShader.cpp
source/MaterialXShaderGen/SgNode.cpp
source/MaterialXShaderGen/SgOptions.cpp
source/MaterialXShaderGen/SgOptions.h
source/MaterialXShaderGen/Shader.cpp
source/MaterialXTest/ShaderGen.cpp

- Added support for creating complete shader interfaces, with uniforms for all used nodes 
- Added option for generating complete vs. reduced shader interface

Support for creating complete shader interface

---

source/MaterialXTest/ShaderValid.cpp

This is a first pass at adding data-driven testing. Still some missing pieces that we want to add to this, but this should make it easy for Bernard and I to extend things.

Adsk contrib/data driven testing

---

documents/TestSuite/stdlib/geometric/streams.mtlx
source/MaterialXShaderGen/Util.cpp
source/MaterialXShaderGen/Util.h
source/MaterialXTest/CMakeLists.txt
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

- Add in a test geometry streams test on disk
- Install this, or any files in the "TestSuite" directory to the test directory.
- Fix up import libraries so that top level elements are tagged and skipped when trying to determine what to run validation on.
- Move directory scan to Utils

Updates to validation framework

---

source/MaterialXGenOsl/OslSyntax.cpp

Small fix to roughnessinfo default value initialization.

roughnessinfo default value fix

---

documents/TestSuite/sxpbrlib/multioutput/multioutput.mtlx
source/MaterialXGenShader/Nodes/CompoundNode.cpp

- Add in missing multioutput support to CompoundNode
- Add more test cases for multioutput support to the test suite

Fixed issue with multioutput when used in node implementation graphs.

---

documents/Libraries/sxpbrlib/sx-glsl/lib/sx_math.glsl
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

- Fixed bug in GLSL epsilon compare functions. 
- Small change to shader output file naming.

Small bugfix and cleanup

---

documents/TestSuite/_options.mtlx
source/MaterialXRender/ShaderValidators/Glsl/GlslValidator.cpp
source/MaterialXRender/ShaderValidators/Glsl/GlslValidator.h
source/MaterialXRender/ShaderValidators/Osl/OslValidator.cpp
source/MaterialXRender/ShaderValidators/Osl/OslValidator.h
source/MaterialXRender/ShaderValidators/ShaderValidator.h
source/MaterialXTest/ShaderValid.cpp

- Minor changes to try and make GLSl and OSL renders closer in render parameters
- Add in timers to and dump out profile times to log.

Cleanup unit test options and and in profile timer framework

---

documents/Libraries/stdlib/sx-osl/mx_geomattrvalue_color2.osl
documents/Libraries/stdlib/sx-osl/mx_geomattrvalue_color3.osl
documents/Libraries/stdlib/sx-osl/mx_geomattrvalue_vector2.osl
documents/Libraries/stdlib/sx-osl/mx_geomattrvalue_vector3.osl
documents/Libraries/stdlib/sx-osl/mx_geomattrvalue_vector4.osl
documents/TestSuite/_options.mtlx
documents/TestSuite/stdlib/geometric/geomattrvalue.mtlx
source/MaterialXCore/Node.cpp
source/MaterialXCore/Node.h
source/MaterialXGenGlsl/Nodes/GeomAttrValueNodeGlsl.cpp
source/MaterialXGenShader/ColorManagementSystem.cpp
source/MaterialXGenShader/ColorManagementSystem.h
source/MaterialXGenShader/ShaderGenerator.h
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

Find out which implementations don't have a unit test yet in ShaderValid.
Should be 0 when all tests have been added.

Add in implementation usage check for ShaderValid

---

documents/TestSuite/stdlib/application/syntax.mtlx
source/MaterialXGenGlsl/GlslSyntax.cpp
source/MaterialXGenShader/Syntax.cpp
source/MaterialXGenShader/Syntax.h

Add invalid token checker for Syntax and add in tokens for GLSL and unit test.

Add invalid token re-mapper for language Syntax. 

---

documents/Libraries/stdlib/stdlib_ng.mtlx

Fix graph implementations of the tiledimage node

---

.appveyor.yml
source/MaterialXRender/Handlers/stbImageLoader.cpp

- Merge stb fixes made in shaderx back.
- Add back in win32 test and deploy on shaderx builds.

Merge stb fixes back to dev

---

documents/Libraries/stdlib/cm_sx-glsl_impl.mtlx
documents/Libraries/stdlib/cm_sx-osl_impl.mtlx
documents/Libraries/stdlib/sx-glsl/mx_srgb_texture_to_linear_color3.glsl
documents/Libraries/stdlib/sx-glsl/mx_srgb_texture_to_linear_color4.glsl
documents/Libraries/stdlib/sx-osl/mx_srgb_texture_to_linear_color3.osl
documents/Libraries/stdlib/sx-osl/mx_srgb_texture_to_linear_color4.osl
documents/TestSuite/stdlib/color_management/color_management.mtlx

Renamed sRGB colorspace to srgb_texture, also renamed ACEScg color space

---

source/MaterialXRender/Handlers/TinyObjLoader.cpp

Minor fixes for memory allocation and access.

Tiny Obj Loader fixes

---

source/MaterialXGenShader/Shader.cpp

Improve robustness of GLSL include logic

---

source/MaterialXRender/Handlers/GeometryHandler.cpp

Fix for mesh bounds computation for geometryhandler.

Mesh bounds fix for GeometryHandler

---

source/MaterialXGenShader/Syntax.cpp
source/MaterialXTest/ShaderGen.cpp
source/MaterialXTest/ShaderValid.cpp

Floats have float syntax now (not ints) and 3x3 matrix tests are

---

source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp
source/MaterialXGenShader/Syntax.cpp
source/MaterialXTest/ShaderGen.cpp

Moved float formatting control to GLSL shader generator.

Update to float formatting.

---

CHANGELOG.md
documents/Examples/SubGraphs.mtlx
source/MaterialXCore/Element.h
source/MaterialXCore/Geom.h
source/MaterialXCore/Interface.cpp
source/MaterialXCore/Interface.h

Review changes resulting from merge to ILM master. Reviewed by ILM during merge.

Update dev based on ILM master changes

---

CHANGELOG.md
documents/Libraries/stdlib/osl/README.md
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXCore/Geom.h
source/MaterialXCore/Interface.cpp
source/MaterialXCore/Interface.h
source/MaterialXTest/Geom.cpp
source/MaterialXTest/Look.cpp
source/MaterialXTest/XmlIo.cpp
source/PyMaterialX/PyDocument.cpp

Merge from ILM master to dev

---

python/MaterialXTest/shaderx.py
source/MaterialXGenOsl/OslShaderGenerator.h
source/MaterialXGenShader/DefaultColorManagementSystem.h
source/PyMaterialX/CMakeLists.txt
source/PyMaterialX/PyColorManagement.cpp
source/PyMaterialX/PyFile.cpp
source/PyMaterialX/PyGenOptions.cpp
source/PyMaterialX/PyGenShaderUtil.cpp
source/PyMaterialX/PyHwLightHandler.cpp
source/PyMaterialX/PyHwShader.cpp
source/PyMaterialX/PyMaterialX.cpp
source/PyMaterialX/PyShader.cpp
source/PyMaterialX/PyShaderGenerator.cpp

Currently all of the files are a part of a single library. After speaking with @bernardkwok , I'll look into splitting this up into multiple libs in the next review.
Also, I currently have a single test which is a port from ShaderGen, but will look into adding a ported version of the main ShaderValid test soon.

Adds ShaderX Python Wrappers.

---

source/MaterialXRender/Handlers/TestObjLoader.cpp
source/MaterialXRender/Handlers/TestObjLoader.h
source/MaterialXRender/Window/SimpleWindow_linux.cpp

Fix Codacy errors for MaterialXRender module.

Fix Codacy errors for MaterialXRender module.

---

documents/Libraries/stdlib/genglsl/mx_transformpoint2_matrix33.glsl
documents/Libraries/stdlib/genglsl/mx_transformpoint3_matrix44.glsl
documents/Libraries/stdlib/genglsl/mx_transformvector2_matrix33.glsl
documents/Libraries/stdlib/genglsl/mx_transformvector3_matrix44.glsl
documents/Libraries/stdlib/genglsl/stdlib_genglsl_impl.mtlx
documents/Libraries/stdlib/genosl/mx_transformpoint2_matrix33.osl
documents/Libraries/stdlib/genosl/mx_transformpoint3_matrix44.osl
documents/Libraries/stdlib/genosl/mx_transformvector2_matrix33.osl
documents/Libraries/stdlib/genosl/stdlib_genosl_impl.mtlx
documents/Libraries/stdlib/stdlib_defs.mtlx
documents/TestSuite/_options.mtlx
documents/TestSuite/stdlib/math/transform.mtlx

- Add in transformpoint(vec2, materix33), transformpoint(vec3, materix44)
- Fix up transformvector versions of these to last coord 0.0 vs 1.0.

Add in support for transformpoint v2*m33 and v3*m44

---

.appveyor.yml
.travis.yml
python/MaterialX/colorspace.py
python/MaterialX/datatype.py
python/MaterialXTest/genshader.py
python/MaterialXTest/main.py
source/PyMaterialX/PyMaterialXGenShader/PyColorManagement.cpp

Python fixes for issues found via PyLint.

Python fixes for issues found via PyLint.

---

source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/Nodes/CompoundNode.cpp
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/Syntax.cpp
source/MaterialXGenShader/Syntax.h

Add in a custom "make valid name" method to replace invalid characters with underscores.
Also calls to replace invalid tokens.

Handle namespace characters and other invalid chars / tokens for function names.

---

documents/DeveloperGuide/ShaderGeneration.md
documents/Libraries/pbrlib/pbrlib_defs.mtlx
documents/Libraries/pbrlib/pbrlib_ng.mtlx
documents/README.md
source/MaterialXTest/README.md
source/PyMaterialX/README.md
source/README.md

Documentation cleanup

---

documents/DeveloperGuide/ShaderGeneration.md
documents/Libraries/README.md
source/README.md

Markdown cleanup for source directory, libraries. Minor update for ShaderGeneration doc.

README folder cleanup

---

documents/Libraries/stdlib/stdlib_defs.mtlx
documents/Libraries/stdlib/stdlib_ng.mtlx
documents/TestSuite/stdlib/math/transform.mtlx

Merge in new place2d nodedef + implementation and add a test.

Merge in place2d definition

---

README.md
resources/README.md
source/MaterialXTest/GenOsl.cpp
source/README.md

Small light filter fixes for OSL test + docs updates.

OSL test fix and minor doc updates.

---

CMakeLists.txt
libraries/stdlib/stdlib_defs.mtlx
resources/CMakeLists.txt
source/MaterialXCore/Document.h
source/MaterialXCore/Geom.cpp
source/MaterialXCore/Geom.h
source/MaterialXGenShader/ShaderGraph.cpp
source/PyMaterialX/PyMaterialXCore/PyGeom.cpp

- Updated GeomPropDef element to match specification.
- Fixed copy of resources director by INSTALL.

Updates to GeomPropDef element.

---

libraries/stdlib/genglsl/mx_add_surfaceshader.glsl
libraries/stdlib/genglsl/mx_mix_surfaceshader.glsl
libraries/stdlib/genglsl/mx_multiply_surfaceshader_color3.glsl
libraries/stdlib/genglsl/mx_multiply_surfaceshader_float.glsl
libraries/stdlib/genglsl/stdlib_genglsl_impl.mtlx
libraries/stdlib/genosl/stdlib_genosl_impl.mtlx
source/MaterialXTest/CMakeLists.txt
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h

Add in missing add, multiply and mix shader implementations for genglsl.

Add in GLSL surfaceshader math operation support

---

source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp
source/MaterialXGenOgsFx/OgsFxShaderGenerator.h
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/Render.cpp
source/PyMaterialX/PyMaterialXGenOgsFx/PyOgsFxShaderGenerator.cpp

Fix up FX_STAGE so that it's in the Stage namespace to be consistent with other stage names.

Rename HW:FX_STAGE to Stage::FX_STAGE

---

source/MaterialXTest/Render.cpp

- Fix so we catch all MaterialX exceptions instead of crashing
- Fix up to v-flip images for OpenGL

Render test cleanup

---

libraries/pbrlib/pbrlib_defs.mtlx
libraries/pbrlib/pbrlib_ng.mtlx
source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXCore/Interface.cpp
source/MaterialXCore/Interface.h
source/MaterialXGenShader/Syntax.cpp
source/MaterialXRender/Handlers/ImageHandler.cpp
source/MaterialXRender/Handlers/ImageHandler.h
source/MaterialXRender/Handlers/OiioImageLoader.cpp
source/MaterialXRender/Handlers/OiioImageLoader.h
source/MaterialXView/CMakeLists.txt

- Merge from master and viewer fork
- Merge back of "channels" changes.

Misc merges from ILM master and viewer fork

---

source/MaterialXView/Editor.cpp
source/MaterialXView/Editor.h
source/MaterialXView/Material.cpp
source/MaterialXView/Material.h

Transparency fix and editabilty based on program uniform existence check added.

Fix viewer transparency and editability of program uniform detection

---

source/MaterialXView/Material.cpp

Reverse incorrect logic to fix up direct lighting toggle.

Fix viewer direct lighting toggle.

---

LICENSE.txt
libraries/README.md
libraries/stdlib/genglsl/lib/mx_noise.glsl
resources/Materials/TestSuite/README.md
source/MaterialXView/Editor.cpp

Misc updates back from RV PR to dev.

Misc updates back from RV PR to dev

---

source/MaterialXView/Editor.cpp
source/MaterialXView/Editor.h

Add in float sliders and custom color picker.

More UI cleanup for property editor

---

.gitignore
libraries/bxdf/standard_surface.mtlx
libraries/pbrlib/genglsl/mx_mix_bsdf.glsl
libraries/pbrlib/genglsl/mx_mix_edf.glsl
libraries/pbrlib/pbrlib_defs.mtlx
libraries/stdlib/genglsl/mx_mix_surfaceshader.glsl
resources/Materials/Examples/StandardSurface/standard_surface_brass_tiled.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_carpaint.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_chrome.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_copper.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_gold.mtlx
resources/Materials/TestSuite/pbrlib/bsdf/bsdf_graph.mtlx

- Fixed bugs with mix nodes.
- Fixed bugs in standard_surface graph.
- Fixed errors in standard_surface examples.

Fixed bugs with mix node implementations and usage.

---

resources/Materials/TestSuite/stdlib/geometric/streams.mtlx

- Added test for object space position and normal
- Simplified uv test using channels attribute for swizzling

Improved streams test

---

resources/Materials/TestSuite/stdlib/color_management/surface_colorspace.mtlx
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/ShaderNode.cpp
source/MaterialXGenShader/ShaderNode.h

Fixed bug with CM on node inputs.

---

python/MaterialXTest/tests_to_html.py

New tool for converting the test results to an HTML page.

---

python/MaterialXTest/tests_to_html.py

Update #416.
- Use argparser instead of using manual parsing.
- Add in image width, cellpadding, and tableborder width options.

Additional format options for html creation

---

source/MaterialXCore/Types.cpp
source/MaterialXCore/Types.h
source/MaterialXRender/Mesh.cpp

routines for different types of data (points/vectors/normals).

Changes the Matrix44 Vector4 multiply routine into several tranform

---

resources/Materials/Examples/StandardSurface/standard_surface_shaderball_base.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_shaderball_sphere.mtlx
resources/Materials/Examples/StandardSurface/test_look.mtlx
source/MaterialXView/Main.cpp

Update #426
- Add in Arnold shader ball geometry (ma, and obj)
- Add in default base + sphere materials
- Modify test Look to use these defaults and assign the example Brass material to the shell and ring.
- Modify the Viewer to use the new geometry as the default.

Add in Arnold Shader Ball geometry

---

resources/Materials/TestSuite/stdlib/math/math.mtlx
resources/Materials/TestSuite/stdlib/math/math_operators.mtlx
resources/Materials/TestSuite/stdlib/math/transform.mtlx
source/MaterialXGenOsl/OslSyntax.cpp

Math and transform test fixes.

---

source/MaterialXGenGlsl/GlslSyntax.cpp
source/MaterialXGenOsl/OslSyntax.cpp

Fix for avoiding div by zero from surface roughness

---

libraries/stdlib/stdlib_defs.mtlx

Add Bobject and Bworld geomprops that are mapped to Node:` <bitangent>`
e.g.  `<input name="Bw" type="vector3" defaultgeomprop="Bobject" />`

Add BiTangent geomprop

---

source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.cpp
source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.h

Just a minor refactoring to simplify some things.

 Refactoring in MaterialXShadingNodeImpl.

---

source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.cpp
source/MaterialXRender/ImageHandler.cpp
source/MaterialXRender/ImageHandler.h
source/MaterialXView/Material.cpp

* Add UDIM utilities for file name resolves and to get tile numbers.
* Use resolvers in plug-in and viewer.

Add UDIM image filename utilities

---

cmake/modules/FindMaterialX.cmake
python/MaterialXTest/genshader.py
python/MaterialXTest/main.py
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXFormat/XmlIo.cpp
source/MaterialXFormat/XmlIo.h
source/MaterialXRenderGlsl/GLTextureHandler.cpp
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/XmlIo.cpp
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXCore/PyDocument.cpp
source/PyMaterialX/PyMaterialXCore/PyElement.cpp
source/PyMaterialX/PyMaterialXFormat/PyXmlIo.cpp

Update #460 
* Handling for duplicate library imports
* Reverse merge of dev/
* Trilinear filter for viewer.

Master to dev update - July 3

---

python/MaterialXTest/main.py
source/MaterialXContrib/MaterialXNode/MaterialXUtil.cpp
source/MaterialXContrib/MaterialXNode/MaterialXUtil.h
source/MaterialXCore/Document.cpp
source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXFormat/XmlIo.cpp
source/MaterialXFormat/XmlIo.h
source/MaterialXGenShader/Util.cpp
source/MaterialXGenShader/Util.h
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenOgsXml.cpp
source/MaterialXTest/GenShader.cpp
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/GenShaderUtil.h
source/MaterialXTest/RenderArnold.cpp
source/MaterialXTest/RenderGLSL.cpp
source/MaterialXTest/RenderOSL.cpp
source/MaterialXTest/RenderOgsFx.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/RenderUtil.h
source/MaterialXTest/XmlIo.cpp
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXCore/PyElement.cpp
source/PyMaterialX/PyMaterialXFormat/PyXmlIo.cpp

- New duplicate element conflict logic merge.

Merge from ILM master.

---

source/MaterialXContrib/MaterialXNode/AEtemplate/AEMaterialXSurfaceTemplate.mel
source/MaterialXContrib/MaterialXNode/CMakeLists.txt
source/MaterialXContrib/MaterialXNode/Plugin.cpp
source/MaterialXContrib/MaterialXNode/ReloadMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/ReloadMaterialXNodeCmd.h
source/MaterialXContrib/MaterialXNode/mods/MaterialXNode.mod
source/MaterialXContrib/MaterialXNode/scripts/MaterialXNodeUtil.py

Note: reload currently calls an empty command.

Adds reload and edit buttons to the MaterialXNode.

---

source/MaterialXContrib/MaterialXNode/AEtemplate/AEMaterialXSurfaceTemplate.mel
source/MaterialXContrib/MaterialXNode/CMakeLists.txt
source/MaterialXContrib/MaterialXNode/Plugin.cpp
source/MaterialXContrib/MaterialXNode/ReloadMaterialXNodeCmd.cpp
source/MaterialXContrib/MaterialXNode/ReloadMaterialXNodeCmd.h
source/MaterialXContrib/MaterialXNode/mods/MaterialXNode.mod
source/MaterialXContrib/MaterialXNode/scripts/MaterialXNodeUtil.py

* Adds reload and edit buttons to the MaterialXNode.
Note: reload currently calls an empty command.
* Applied code review feedback.
* Applied additional code review feedback.

Adds reload and edit buttons to the MaterialXNode. (#519)

---

libraries/stdlib/genglsl/lib/mx_transform_uv_vflip.glsl
libraries/stdlib/genosl/lib/mx_transform_uv_vflip.osl
source/MaterialXContrib/MaterialXNode/MaterialXData.cpp
source/MaterialXContrib/MaterialXNode/MaterialXData.h
source/MaterialXContrib/MaterialXNode/MaterialXShadingNodeImpl.cpp
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp
source/MaterialXGenOgsXml/GlslFragmentGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/ShaderGenerator.cpp

Fixes #MATX-232
Workaround to always bind matrices since XML -> OGSFX does not set values properly.

MATX-232 : Add explicit matrix binding workaround for XML->OGSFX lack of value transfer

---

source/MaterialXGenShader/Util.cpp

Fix #551.
Fix test for transparency when opacity or transmission have interface names in a nodegraph nodedef.
Check the actual values / connections for any bindinputs which are using these interface names on the shaderref.
This is the problem case. First the nodegraph for the nodedef looks likes this:
```
<standard_surface name="standard_surface0" type="surfaceshader">
<input name="normal" type="vector3" value="1, 1, 1" defaultgeomprop="Nobject" interfacename="surface_normal" />
<input name="opacity" type="color3" value="1, 1, 1" interfacename="surface_cutout" />
<input name="specular_color" type="color3" value="1, 1, 1" interfacename="surface_albedo" />
<input name="specular_roughness" type="float" nodename="specular_roughness_value" />
<input name="specular_anisotropy" type="float" …
```

Transparency parameter interfacename check logic

---

source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXRender/Util.cpp
source/MaterialXRender/Util.h
source/MaterialXView/Editor.cpp
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

MATX-214 : Add advanced ui attribute

---

source/MaterialXContrib/MaterialXMaya/README.md

…d intermediate file dump path.

MATX-236 - README.md: reloading libraries, configurable resource search paths and intermediate file dump path.

---

libraries/stdlib/genglsl/mx_length_unit.glsl
libraries/stdlib/genglsl/stdlib_genglsl_unit_impl.mtlx
resources/Materials/Examples/Units/distance_units.mtlx
resources/Materials/Examples/Units/standard_surface_unit.mtlx
resources/Materials/Examples/Units/texture_units.mtlx
source/MaterialXCore/UnitConverter.cpp
source/MaterialXGenShader/GenOptions.h
source/MaterialXGenShader/ShaderGenerator.h
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/ShaderGraph.h
source/MaterialXGenShader/UnitSystem.cpp
source/MaterialXGenShader/UnitSystem.h
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenOgsXml.cpp
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/RenderUtil.cpp
source/MaterialXTest/RenderUtil.h
source/MaterialXTest/Units.cpp
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

Basic Shader based unit conversion
- Add a unit system
- Add glsl impl

Shader based unit conversion

---

resources/Materials/Examples/Units/distance_units.mtlx
source/MaterialXCore/UnitConverter.cpp
source/MaterialXCore/UnitConverter.h
source/MaterialXTest/Units.cpp
source/PyMaterialX/PyMaterialXCore/PyUnitConverter.cpp

Also updated the python binding and test case.

Add convenience helpers for LengthUnitConverter::convert

---

source/MaterialXGenShader/UnitSystem.cpp
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

Remove the list of available units and source them from the LengthConverter.
Fix the bug in scale conversion in shader.

Update UI to use unit enumeration and fix bug in scale

---

libraries/bxdf/standard_surface.mtlx

Added support for specular and coat anisotropic rotation.

Improved Standard Surface nodegraph implementation

---

source/MaterialXRuntime/Private/PrvElement.cpp
source/MaterialXRuntime/Private/PrvElement.h
source/MaterialXRuntime/Private/PrvNode.cpp
source/MaterialXRuntime/Private/PrvNode.h
source/MaterialXRuntime/Private/PrvNodeDef.cpp
source/MaterialXRuntime/Private/PrvNodeDef.h
source/MaterialXRuntime/Private/PrvNodeGraph.cpp
source/MaterialXRuntime/Private/PrvNodeGraph.h
source/MaterialXRuntime/Private/PrvObject.cpp
source/MaterialXRuntime/Private/PrvPortDef.h
source/MaterialXRuntime/Private/PrvStage.cpp
source/MaterialXRuntime/Private/PrvStage.h
source/MaterialXRuntime/Private/PrvTraversal.cpp
source/MaterialXRuntime/Private/PrvTraversal.h
source/MaterialXRuntime/RtCoreIo.cpp
source/MaterialXRuntime/RtNode.cpp
source/MaterialXRuntime/RtNode.h
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXRuntime/RtObject.cpp
source/MaterialXRuntime/RtObject.h
source/MaterialXRuntime/RtPortDef.cpp
source/MaterialXRuntime/RtPortDef.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXTest/Runtime.cpp

- Improved element hierarchy
- Improved RtNodeGraph API
- Various bug fixes and code cleanups

Adsk contrib/rt sandbox element hierarchy

---

source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.h
source/MaterialXGenOsl/OslSyntax.cpp
source/MaterialXGenShader/Nodes/ConvolutionNode.cpp
source/MaterialXGenShader/ShaderGraph.cpp
source/MaterialXGenShader/ShaderNode.h
source/MaterialXTest/GenReference.cpp

- added compilation test to generated shaders
- added generation of default genom props at shader input initialization
- fixed bugs with reserved works being used as identifiers

Improvements to OSL reference library generation

---

libraries/stdlib/stdlib_defs.mtlx
libraries/stdlib/stdlib_ng.mtlx
resources/Materials/TestSuite/stdlib/units/tiledimage_unit.mtlx

Update #460 
- Fix up nodegraph implementation for tiled image as part of migration.
- Add in test file.

Migrate over unit inputs for tiledimage.

---

source/MaterialXRuntime/Private/PrvPath.cpp
source/MaterialXRuntime/Private/PrvPath.h
source/MaterialXRuntime/RtPath.cpp
source/MaterialXRuntime/RtPath.h
source/MaterialXTest/Runtime.cpp

Added RtPath class for identification of objects in a stage hierarchy.

---

.travis.yml
source/MaterialXRenderGlsl/CMakeLists.txt
source/MaterialXView/CMakeLists.txt

Mac build fixes from ILM master (See https://github.com/materialx/MaterialX/pull/329/files)

Mac OS Build Improvements

---

source/MaterialXRuntime/Private/PvtNode.cpp
source/MaterialXRuntime/Private/PvtNode.h
source/MaterialXRuntime/Private/PvtNodeDef.h
source/MaterialXRuntime/Private/PvtNodeGraph.cpp
source/MaterialXRuntime/Private/PvtTypeDef.cpp
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtTypeDef.cpp
source/MaterialXRuntime/RtTypeDef.h
source/MaterialXRuntime/RtValue.cpp
source/MaterialXRuntime/RtValue.h
source/MaterialXTest/Runtime.cpp

- Added method for true semantic compare of RtValues.
- Fixed bug with how values where created and initialized on node instances.

Fixed issues with creation and compare of RtValues

---

CHANGELOG.md
source/MaterialXRenderGlsl/GlslProgram.cpp
source/MaterialXView/Editor.cpp

Minor ILM master updates for 1.37

---

libraries/stdlib/stdlib_defs.mtlx
python/MaterialXTest/main.py
source/MaterialXCore/Document.cpp
source/MaterialXCore/Types.cpp
source/MaterialXCore/Types.h
source/MaterialXGenShader/TypeDesc.cpp
source/MaterialXGenShader/TypeDesc.h
source/MaterialXRuntime/Private/PvtTypeDef.cpp
source/MaterialXRuntime/RtTypeDef.cpp
source/MaterialXRuntime/RtTypeDef.h
source/MaterialXTest/GenArnold.cpp
source/MaterialXTest/GenGlsl.cpp
source/MaterialXTest/GenGlsl.h
source/MaterialXTest/GenOgsXml.cpp
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenOsl.cpp
source/MaterialXTest/GenOsl.h
source/MaterialXTest/GenShaderUtil.cpp
source/MaterialXTest/XmlIo.cpp
source/MaterialXView/Material.cpp

Add in "surfacematerial" + "volumematerial" node definitions + "material" type for runtime usage.

LOOKDEVX-4 : material node definition

---

python/Scripts/genmdl.py

- Add in color4 type and default geomprop value setting.
- Skip organization nodes
- Dump unsupported information as annotations.
- Misc fixes.

Updates to MDL signature creation script

---

source/MaterialXCore/Interface.cpp
source/MaterialXCore/Interface.h
source/MaterialXCore/Node.cpp
source/MaterialXCore/Node.h
source/MaterialXTest/GenOgsfx.cpp
source/MaterialXTest/GenReference.cpp
source/MaterialXTest/Observer.cpp
source/MaterialXTest/XmlIo.cpp

Update #616 
- virtualize connection traversal interfaces to allow node inputs to traverse through to nodegraphs
- Update misc tests.

Node to NodeGraph connection updates

---

source/MaterialXRuntime/Private/PvtStageManager.cpp
source/MaterialXRuntime/Private/PvtStageManager.h
source/MaterialXRuntime/RtStageManager.cpp
source/MaterialXRuntime/RtStageManager.h

Adds a stages getter and a rename method.

Adsk contrib/stage manager stages getter

---

libraries/stdlib/genmdl/cm.mdl
libraries/stdlib/genmdl/stdlib_genmdl_cm_impl.mtlx

MDL support for basic color transforms

---

source/MaterialXRuntime/Private/PvtPrim.cpp
source/MaterialXRuntime/Private/PvtPrim.h
source/MaterialXRuntime/Private/PvtStage.cpp
source/MaterialXRuntime/Private/PvtStage.h
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h
source/MaterialXRuntime/RtBackdrop.cpp
source/MaterialXRuntime/RtBackdrop.h
source/MaterialXRuntime/RtCollection.cpp
source/MaterialXRuntime/RtCollection.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtGeneric.cpp
source/MaterialXRuntime/RtGeneric.h
source/MaterialXRuntime/RtLook.cpp
source/MaterialXRuntime/RtLook.h
source/MaterialXRuntime/RtNode.cpp
source/MaterialXRuntime/RtNode.h
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXRuntime/RtObject.h
source/MaterialXRuntime/RtPrim.cpp
source/MaterialXRuntime/RtPrim.h
source/MaterialXRuntime/RtSchema.cpp
source/MaterialXRuntime/RtSchema.h
source/MaterialXRuntime/RtToken.h
source/MaterialXRuntime/RtTypeInfo.cpp
source/MaterialXRuntime/RtTypeInfo.h
source/MaterialXTest/Runtime.cpp

Need proper run time type information in order to create typed schemas derived from other typed schemas.

Fix proper RTTI for typed schemas.

---

libraries/stdlib/genmdl/hsv.mdl
libraries/stdlib/genmdl/vectormatrix.mdl
python/Scripts/genmdl.py

Generate non-complex functions.

Generated implementations for MDL

---

source/MaterialXRuntime/RtFileIo.cpp

Fixed material elements serialization from the runtime in compatibility mode.

Fixed material elements serialization

---

libraries/stdlib/genmdl/materialx/vectormatrix.mdl
libraries/stdlib/genmdl/stdlib_genmdl_impl.mtlx
python/Scripts/genmdl.py
source/MaterialXTest/GenShaderUtil.cpp

- fill in more implementations
- fix up function call specified for determinant impl.

MDL stdlib implementation updates

---

libraries/stdlib/genglsl/lib/mx_noise.glsl
libraries/stdlib/genmdl/stdlib_genmdl_impl.mtlx
source/MaterialXGenMdl/mdl/materialx/noise.mdl
source/MaterialXTest/CMakeLists.txt
source/MaterialXView/CMakeLists.txt
source/MaterialXView/Editor.cpp
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h

- Fixup noise inconsistencies
- Added export of Maya GLSL/OGSFX shaders from viewer

Fixup noise inconsistencies

---

resources/Materials/TestSuite/stdlib/upgrade/material_element_to_surface_material.mtlx
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXTest/Runtime.cpp

correctly by the MaterialX runtime.

Fixes a bug related to node graph connections not beingn processed

---

source/MaterialXRenderGlsl/GlslProgram.cpp

Fixes a GPU memory leak.

---

libraries/bxdf/standard_surface.mtlx
libraries/bxdf/usd_preview_surface.mtlx
libraries/pbrlib/pbrlib_defs.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_default.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_emission.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_glass.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_greysphere.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_greysphere_calibration.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_jade.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_velvet.mtlx
resources/Materials/TestSuite/libraries/sd/floor.mtlx
resources/Materials/TestSuite/pbrlib/bsdf/transmission.mtlx
resources/Materials/TestSuite/pbrlib/surfaceshader/nodegraph_standardsurface.mtlx
resources/Materials/TestSuite/stdlib/units/standard_surface_unit.mtlx
source/MaterialXGenMdl/MdlShaderGenerator.cpp
source/MaterialXGenMdl/MdlShaderGenerator.h
source/MaterialXGenShader/ShaderGenerator.h
source/MaterialXGenShader/ShaderGraph.cpp

- Change back IOR from parameter to input
- Add breaking connections to transmission IOR as a temporary workaround to the IOR problem

Workaround for limitation with transmission IOR being uniform.

---

source/MaterialXRuntime/Private/PvtObject.h
source/MaterialXRuntime/Private/PvtPrim.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

* Dispose tagging fix 
* Also make debug/ndebug behave the same.

Runtime dispose fixes

---

source/MaterialXRuntime/Private/PvtPrim.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtNode.cpp
source/MaterialXRuntime/RtNode.h
source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtPrim.cpp
source/MaterialXRuntime/RtPrim.h

- Added support for writing explicit inputs/parameters in nodegraph export.
- Added methods for input/output count on prims and nodes.

Support for explicit inputs/parameters in nodegraph export.

---

source/MaterialXGenShader/ShaderGraph.cpp

Fix regression with nodegraph impls in OSL reference generation.

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtStage.cpp

Writes nodegraph uifolder as well as copies uifolder to nodedef and

---

source/MaterialXRuntime/Private/PvtApi.h
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h

Add user definition path storage to runtime global.

LOOKDEVX-207 : Add user definition path

---

source/MaterialXGenShader/Util.cpp
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXView/Viewer.cpp

- Merge ILM transparency fix
- Also fix so that viewer uses the latest version again (was overwritten).
- Libraries also need latest version so fix and fix in runtime as well.

Merge ILM transparency fix

---

source/MaterialXTest/MaterialXGenGlsl/GenGlsl.cpp
source/PyMaterialX/PyMaterialXGenGlsl/PyGlslShaderGenerator.cpp
source/PyMaterialX/PyMaterialXGenGlsl/PyModule.cpp
source/PyMaterialX/PyMaterialXGenShader/PyGenContext.cpp
source/PyMaterialX/PyMaterialXGenShader/PyHwShaderGenerator.cpp
source/PyMaterialX/PyMaterialXGenShader/PyModule.cpp

Add TESTCASE: "GenShader: GLSL Shader with Layout Generation"

Test case and python bindings

---

source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXGenShader/Nodes/LayerNode.h

Fix regression in layering code

---

resources/Materials/TestSuite/stdlib/upgrade/1_37_to_1_38.mtlx
source/MaterialXCore/Document.cpp
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXTest/MaterialXCore/Document.cpp

Makes it so that on read when an interface name has a matching node

---

README.md
source/MaterialXContrib/Handlers/TinyEXRImageLoader.cpp
source/MaterialXRender/Image.h
source/MaterialXRender/ShaderRenderer.h
source/MaterialXRenderGlsl/GlslRenderer.cpp
source/MaterialXRenderGlsl/GlslRenderer.h
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h
source/MaterialXRenderOsl/OslRenderer.cpp
source/MaterialXRenderOsl/OslRenderer.h
source/MaterialXView/Main.cpp

Regular ILM merge update.
- Update image placement in README
- Load standard libraries regardless of build folder location. This changelist fixes a dependency on the build folder being located within the repository root folder.
- Add support for floating-point render targets. This changelist adds support for floating-point render targets in ShaderRenderer and its subclasses, allowing for HDR texture baking with TextureBaker.

Merge update from ILM

---

source/MaterialXRuntime/Private/PvtAttribute.h
source/MaterialXRuntime/RtAttribute.cpp
source/MaterialXRuntime/RtAttribute.h
source/MaterialXRuntime/RtStage.cpp

Adds support for setting the uniform flag on inputs and enables

---

source/JsMaterialX/JsMaterialXCore/JsElement.js
source/JsMaterialX/JsMaterialXCore/JsInterface.js
source/JsMaterialX/JsMaterialXCore/JsValue.js
source/JsMaterialX/initMaterialX.js
source/JsMaterialX/test/basics.spec.js
source/JsMaterialX/test/testHelpers.js

Related to: https://github.com/autodesk-forks/MaterialX/issues/924
- Most of the issues should be fixed. There will still be one issue in the test code.

Fix JavaScript security issues from the Codacy scan

---

resources/Materials/TestSuite/lights/envmap_shader.mtlx
source/MaterialXCore/Document.cpp
source/MaterialXRender/ImageHandler.h
source/MaterialXRenderGlsl/GLTextureHandler.cpp
source/MaterialXRenderGlsl/GLTextureHandler.h
source/MaterialXView/Material.cpp
source/MaterialXView/Material.h
source/MaterialXView/Viewer.cpp

ILM master update ( July 22, 2020 )

---

documents/CMakeLists.txt
python/MaterialXTest/tests_to_html.py
resources/Materials/TestSuite/stdlib/upgrade/1_36_to_1_37.mtlx
source/MaterialXCore/Definition.cpp
source/MaterialXFormat/Util.cpp
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenOsl/OslShaderGenerator.cpp
source/MaterialXGenShader/GenOptions.h
source/MaterialXGenShader/HwShaderGenerator.cpp
source/MaterialXRender/CMakeLists.txt
source/MaterialXRender/Util.cpp
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderOsl/CMakeLists.txt
source/MaterialXRenderOsl/OslRenderer.cpp
source/MaterialXView/Material.cpp
source/MaterialXView/Viewer.cpp

MDL ILM back-merge

---

source/MaterialXRuntime/Private/Commands/PvtConnectionCmd.cpp
source/MaterialXRuntime/Private/PvtAttribute.cpp
source/MaterialXRuntime/Private/PvtPrim.cpp
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtSchema.h

- Transfer uniform flag when creating new interface.
- Check uniform state when validating connections.
- Set uniform on all inputs for filename, token and string types.

Improve ports and connections handling

---

source/MaterialXRuntime/Private/Commands/PvtRemovePrimCmd.cpp
source/MaterialXRuntime/Private/PvtCommand.cpp
source/MaterialXRuntime/RtPrim.cpp
source/MaterialXRuntime/RtPrim.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Fixed issue with removePrim command when the prim had no existing connections.

Fix removePrim command issue

---

source/JsMaterialX/JsMaterialXFormat/JsXmlIo.cpp
source/JsMaterialX/test/codeExamples.spec.js
source/MaterialXCore/Document.cpp
source/MaterialXRuntime/Private/PvtApi.cpp
source/MaterialXRuntime/Private/PvtApi.h
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Add in parameter to input update as option on load / save

---

source/MaterialXRuntime/Private/PvtApi.h
source/MaterialXRuntime/Private/PvtLogger.h
source/MaterialXRuntime/RtApi.cpp
source/MaterialXRuntime/RtApi.h
source/MaterialXRuntime/RtLogger.cpp
source/MaterialXRuntime/RtLogger.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

This is the MaterialX side of the token->string change for logging. Hope this is what you were after.

Change logging to use strings instead of tokens.

---

.travis.yml

Update #1007 (github actions)
Update #963 (WASM)

Reduce travis builds to WASM for PRs

---

source/MaterialXCore/Document.cpp

Update #460 
Patch to apply upgrade if 1.37 or higher vs exactly 1.37

Version patch

---

source/MaterialXCore/Document.cpp
source/MaterialXCore/Element.h

Fix issue with namespaces being applied twice when importing libraries.

---

source/MaterialXRender/ImageHandler.cpp
source/MaterialXRender/ImageHandler.h
source/MaterialXRenderGlsl/GLTextureHandler.cpp
source/MaterialXRenderGlsl/GLTextureHandler.h
source/MaterialXRenderOsl/OslRenderer.cpp
source/PyMaterialX/PyMaterialXRender/PyImageHandler.cpp
source/PyMaterialX/PyMaterialXRenderGlsl/PyGLTextureHandler.cpp

Update #460 
Revert changes for additional "message" argument on ImageHandler as discussed with LucasFilm.
Leave as a stream output for now and discuss later.

Revert ImageHandler message argument changes.

---

libraries/translation/standard_surface_to_UsdPreviewSurface.mtlx
source/MaterialXGenShader/ShaderTranslator.cpp
source/MaterialXGenShader/ShaderTranslator.h
source/MaterialXTest/MaterialXGenShader/GenShader.cpp

Update #974 
Sample test translator (parts of ADSK std surface to USDPreviewSurface)
- Original
- After translation
using an instance of the translator remapper:
defined as:

Update ShaderTranslator to v1.38

---

libraries/bxdf/usd_preview_surface.mtlx

Adding the current version (2.3) and documentation tags for the USDPreviewSurface nodedef.

Add version and doc tags for the USDPreviewSurface shader.

---

source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXTest/MaterialXRenderGlsl/RenderGlsl.cpp

Restore the texture optimization and update testcase to enable `setOptimizeConstants`

Restore Optimization and update TestCase

---

CMakeLists.txt

Visibility cleanup. Docs cleanup.

---

.github/workflows/build_linux.yml
python/MaterialXTest/tests_to_html.py
source/MaterialXContrib/MaterialXMaya/MaterialXUtil.cpp
source/MaterialXContrib/MaterialXMaya/ShadingNodeOverrides.cpp
source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/MaterialXGenGlsl/GlslResourceBindingContext.cpp
source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenGlsl/Nodes/BlurNodeGlsl.h
source/MaterialXGenGlsl/Nodes/GeomPropValueNodeGlsl.cpp
source/MaterialXGenGlsl/Nodes/GeomPropValueNodeGlsl.h
source/MaterialXGenOsl/Nodes/BlurNodeOsl.h
source/MaterialXGenShader/Nodes/ThinFilmNode.h
source/MaterialXGenShader/Syntax.cpp
source/MaterialXRender/GeometryHandler.cpp
source/MaterialXRenderGlsl/GlslRenderer.cpp
source/MaterialXRenderGlsl/GlslRenderer.h
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXRenderGlsl/TextureBaker.h
source/MaterialXTest/MaterialXGenShader/GenShader.cpp
source/MaterialXTest/MaterialXRenderGlsl/RenderGlsl.cpp
source/MaterialXView/Main.cpp
source/MaterialXView/Viewer.cpp
source/MaterialXView/Viewer.h
source/PyMaterialX/PyMaterialXRenderGlsl/PyTextureBaker.cpp

Update #460 
- Back-merge updates from v1.38

LucasFilm v1.38 back-merge

---

libraries/bxdf/usd_preview_surface.mtlx
resources/Materials/Examples/UsdPreviewSurface/usd_preview_surface_brass_tiled.mtlx
resources/Materials/Examples/UsdPreviewSurface/usd_preview_surface_default.mtlx
resources/Materials/Examples/UsdPreviewSurface/usd_preview_surface_glass.mtlx
resources/Materials/Examples/UsdPreviewSurface/usd_preview_surface_gold.mtlx
resources/Materials/Examples/UsdPreviewSurface/usd_preview_surface_plastic.mtlx

Update #1075 1075
Change UsdPreviewSurface "metalness" input to "metallic" which conforms to the spec

Fix UsdPreviewSurface metallic input

---

source/MaterialXRender/ImageHandler.h
source/MaterialXView/Viewer.cpp

IBL update

---

source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/PyMaterialX/PyMaterialXCore/PyUtil.cpp

v1.38 : Restore change child category utility

---

source/MaterialXGenShader/ColorManagementSystem.cpp
source/MaterialXGenShader/ColorManagementSystem.h
source/MaterialXGenShader/DefaultColorManagementSystem.cpp
source/MaterialXGenShader/DefaultColorManagementSystem.h
source/PyMaterialX/PyMaterialXGenShader/PyColorManagement.cpp

Fix issue with CM and target inheritance.

---

.github/workflows/build_linux.yml
CHANGELOG.md
libraries/pbrlib/genglsl/lib/mx_environment_fis.glsl
libraries/pbrlib/genglsl/lib/mx_environment_prefilter.glsl
libraries/pbrlib/genglsl/lib/mx_math.glsl
source/MaterialXCore/Document.cpp
source/MaterialXCore/Element.cpp
source/MaterialXCore/Element.h
source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/MaterialXRender/ImageHandler.h
source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXView/Material.cpp
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXCore/PyElement.cpp
source/PyMaterialX/PyMaterialXCore/PyUtil.cpp

Update #460 
- Sync on v1.38 PR (https://github.com/materialx/MaterialX/pull/574) 
- Sync to latest latest Python test updates and environment mapping changes.
ADSK synced 1:1 with LucasFilm a2e263307f7edd353189cfe51c43b4aa34191580.
[jan_29_2021_render_tests_adsk.pdf](https://github.com/autodesk-forks/MaterialX/files/5896684/jan_29_2021_render_tests_adsk.pdf)

v1.38 update synchronization (@a2e2633)

---

resources/Materials/Examples/StandardSurface/standard_surface_brass_tiled.mtlx
resources/Materials/Examples/StandardSurface/standard_surface_wood_tiled.mtlx

Update #1106.
Revert to remove "../" path usage for now until a resolution is found.

Patch ".." relative paths in unit tests to allow MDL tests to pass

---

libraries/README.md

Doc updates.

---

source/MaterialXFormat/Util.cpp
source/MaterialXFormat/Util.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXTest/MaterialXGenShader/GenShaderUtil.cpp
source/MaterialXView/Viewer.cpp
source/PyMaterialX/PyMaterialXFormat/PyUtil.cpp

Code cleanup for optional arguments in library loading functions.

---

source/MaterialXRenderGlsl/TextureBaker.cpp
source/MaterialXView/Viewer.cpp

Patch fixes for LucasFilm merge.

---

libraries/adsk/adsklib/adsk_colorcorrect.mtlx
libraries/adsk/materials/wood/parquet_3/adsk_parquet_03_material.mtlx
libraries/adsk/shaders/brick/adsk_brick_02_displacementshader.mtlx
libraries/adsk/shaders/brick/adsk_brick_02_surfaceshader.mtlx
libraries/adsk/shaders/brick/adsk_brick_10_displacementshader.mtlx
libraries/adsk/shaders/brick/adsk_brick_10_surfaceshader.mtlx
libraries/adsk/shaders/plastic/adsk_plastic08_red_surfaceshader.mtlx
libraries/adsk/shaders/wood/parquet_3/adsk_parquet_03_displacementshader.mtlx
libraries/adsk/shaders/wood/parquet_3/adsk_parquet_03_surfaceshader.mtlx
resources/Materials/TestSuite/adsklib/adsk_shaders.mtlx
resources/Materials/TestSuite/adsklib/shaders/brick/brick_02_shader_impl.mtlx
resources/Materials/TestSuite/adsklib/shaders/brick/brick_10_shader_impl.mtlx
resources/Materials/TestSuite/adsklib/shaders/wood/parquet_03_shader_impl.mtlx
resources/Materials/TestSuite/translation/standard_surface_to_UsdPreviewSurface.mtlx

Update #460 
Update ADSK files to 1.38 using `mxupdate.py`
Unit Test Results:
[feb23_upgrade_docs.pdf](https://github.com/autodesk-forks/MaterialX/files/6033319/feb23_upgrade_docs.pdf)

v1.38 : Upgrade ADSK Documents

---

source/MaterialXGenShader/DefaultColorManagementSystem.h
source/MaterialXRuntime/RtColorManagementSystem.cpp
source/MaterialXRuntime/RtColorManagementSystem.h

retrieve the default color space names.

LOOKDEVX-407 | Added color management system classes to the runtime to

---

source/MaterialXCore/Document.cpp
source/MaterialXCore/Document.h
source/MaterialXRuntime/RtNodeGraph.cpp
source/MaterialXRuntime/RtNodeGraph.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXRuntime/RtStage.h
source/MaterialXTest/MaterialXCore/Node.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Update #390 
- Add support in core
- Add support in runtime
- Update tests

Add namespace support for nodedef creation from nodegraph

---

source/MaterialXCore/Look.cpp
source/MaterialXCore/Look.h
source/MaterialXCore/Util.cpp
source/MaterialXCore/Util.h
source/MaterialXTest/MaterialXCore/Look.cpp
source/PyMaterialX/PyMaterialXCore/PyLook.cpp
source/PyMaterialX/PyMaterialXCore/PyUtil.cpp

Add in look / lookgroup management utilities
- Add in ability to append a look to another look
- Add ability to merge all looks together in a lookup
- Add ability to merge a lookup into another lookup with the option to skip duplicate looks.
Add string array to string merge utility.
1. Starting configuration
```
<materialx version="1.38">
<lookgroup name="lookgroup1" looks="look1,look2,look3,look4,look5" active="look1" />
<look name="look1">
<materialassign name="matA" material="materialA" />
<materialassign name="matB" material="materialB" />
<materialassign name="matC" material="materialC" />
</look>
<look name="look2">
<materialassign name="matA" material="materialA" />
<materialassign name="matB" material="materialB" />
<materialassign name="matC" …
```

LOOKDEVX-470 : Look  and LookGroup management 

---

libraries/adsk/adsklib/adsklib_ng.mtlx

Remove extract node to address adsk:heightmap - heighttonormal issues.

Fix adsk:heightmap - heighttonormal issues.

---

source/MaterialXTest/MaterialXRender/RenderUtil.cpp
source/MaterialXTest/MaterialXRender/RenderUtil.h
source/MaterialXTest/MaterialXRenderGlsl/RenderGlsl.cpp

Update runBake to accept codesearch path option in addition to texture search path

Baking test update

---

source/MaterialXRuntime/RtFileIo.cpp

LOOKDEVX-460 | Fixes some remaining issues with the importing of look

---

source/MaterialXRuntime/RtNodeDef.cpp
source/MaterialXRuntime/RtNodeDef.h
source/MaterialXRuntime/RtStage.cpp
source/MaterialXRuntime/RtStage.h
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Replace RtIdentifier with std::string when handling doc attribute

Fix the data types related to compound note doc attribute.

---

source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtStage.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

The repository for this project is empty type and version number

t-rusel/LOOKDEVX-421/adjust-node-def-naming

---

libraries/bxdf/usd_preview_surface.mtlx

According to specifications found in:
https://graphics.pixar.com/usd/docs/UsdPreviewSurface-Proposal.html

Fix default value for roughness.

---

source/MaterialXContrib/MaterialXMaya/CreateMaterialXNodeCmd.cpp
source/MaterialXFormat/XmlExport.cpp
source/MaterialXFormat/XmlExport.h
source/MaterialXRuntime/RtFileIo.cpp
source/MaterialXRuntime/RtFileIo.h
source/MaterialXTest/MaterialXFormat/XmlExport.cpp
source/MaterialXTest/MaterialXRuntime/Runtime.cpp

Add option on whether to overwrite the existing document on export + misc init fixes.

Add in overwrite option to export

---

.github/workflows/main.yml

- Only run 3 checks on push
- Only run render, generate and publish on pull requests.

Reduce CI overhead

---

source/JsMaterialX/CMakeLists.txt
source/JsMaterialX/JsMaterialXGenEssl/JsEsslShaderGenerator.cpp
source/JsMaterialX/JsMaterialXGenShader/JsHwShaderGenerator.cpp
source/JsMaterialX/JsMaterialXView/src/helper.js
source/JsMaterialX/JsMaterialXView/src/index.js
source/JsMaterialX/JsMaterialXView/webpack.config.js

Added bindings to load lights
Demonstrates direct lighting setup in JS sample app
Contributes to #1184

Added support for direct lighting in JS

---

source/JsMaterialX/JsMaterialXCore/JsUnit.cpp
source/JsMaterialX/JsMaterialXGenShader/JsGenContext.cpp

Fixed issue with units in materials when js bindings are used
Contributes to #1184

fixed unit registry creation in js bindings

---

source/JsMaterialX/CMakeLists.txt
source/JsMaterialX/JsMaterialXGenShader/JsShader.cpp
source/JsMaterialX/JsMaterialXGenShader/JsShaderNode.cpp
source/JsMaterialX/JsMaterialXGenShader/JsShaderStage.cpp
source/JsMaterialX/JsMaterialXGenShader/JsTypeDesc.cpp
source/JsMaterialX/JsMaterialXView/src/helper.js
source/JsMaterialX/JsMaterialXView/src/index.js
source/JsMaterialX/MapHelper.h
source/MaterialXGenShader/Shader.h
source/MaterialXGenShader/ShaderStage.cpp
source/MaterialXGenShader/ShaderStage.h

Removed the getUniformValues function from ShaderStage and reimplemented it in javascript
Created all necessary JS bindings for it
Update #1184

Ported getUniformValues to JS

---

source/JsMaterialX/JsMaterialXView/src/helper.js

Forgot to update the sample application in the previous PR.

JS Bindings: Fix sample application after removing getValue wrapper

---

source/JsMaterialX/JsMaterialXView/package-lock.json
source/JsMaterialX/JsMaterialXView/package.json
source/JsMaterialX/test/package-lock.json

chore: Address vulnerability issues

---

source/MaterialXGenGlsl/GlslShaderGenerator.cpp
source/MaterialXGenGlsl/GlslShaderGenerator.h
source/MaterialXGenOgsFx/OgsFxShaderGenerator.cpp
source/MaterialXGenOgsXml/GlslFragmentGenerator.cpp

- Update CLOSURE detection in OgsFx and OgsXML
- Restore a specialization used by USD

MATX-338  : Update code for Maya and USD MaterialX codegen

---

.github/workflows/main.yml

V2 has upload problems on windows. Trying patch version 2.2.4.

Patch artifact upload version

---

source/MaterialXView/Main.cpp

Fix viewer code to properly start-up.

1.38.3 Merge fix for viewer

---

source/JsMaterialX/JsMaterialXView/package-lock.json
source/JsMaterialX/JsMaterialXView/package.json

Updated dependencies due to known vulnerabilities in downstream dependencies
Used `npm audit fix` for the changes

Security updates for JS dependencies

---

libraries/stdlib/stdlib_defs.mtlx
libraries/stdlib/stdlib_ng.mtlx
resources/Materials/TestSuite/stdlib/texture/image_transform.mtlx

Cherry pick https://github.com/AcademySoftwareFoundation/MaterialX/pull/1027 to dev branch

Provide a frame transform for UV texture coordinates (#1027)

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx

options and values for enum and ui were off by 1

Wall Paint enum count mismatch

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Adding defaultgeomprop attributes
Unifying default values for vector3 inputs
Fixing wrong normal conversion in Glass graph
Fixing wrong default normal constant in Generic graph

Legacy graphs Normals Fixes

---

contrib/adsk/libraries/adsklib/adsklib_legacy_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_legacy_ng.mtlx

Legacy Waves procedural and 2 utiilty graphs added.
This procedural has a limit of 8 waves. It accepts higher number of waves as input, but will return the max of 8 waves always.

Adding Legacy Waves procedural

---

.github/workflows/automerge.yml

This new GitHub action will try to auto merge main into `adsk_contrib/dev` very week.
If the merge fails, a PR will be created. adding @ashwinbhat, @zicher3d , and @ppenenko as reviewers.

Add automerge action

---

.github/workflows/automerge.yml

This action will run every Saturday to create a branch from `main` and create a PR to merge it into `adsk_contrib/dev`
If the merge branch already exists, then it will merge `main` into it.
This GitHub action can also be executed manually if needed.

GitHub action to merge main into adsk_contrib/dev

---

contrib/adsk/libraries/adsklib/adsklib_defs.mtlx
contrib/adsk/libraries/adsklib/adsklib_ng.mtlx

Changing some inputs to make the graphs more USD friendly. These changes will not affect any of the graphs functionality, they will just shift the default values somewhere else.
Checked the unit tests and there are no changes needed there.
This are changes form Jerry Gamache.

USD compatibility updates
